/*
  Every reference-list example printed in 1215757, as the Zotero data the
  style's own header tells an author to enter, paired with the exact string
  the guide prints. Section numbers refer to the instruction.
*/
module.exports = [
  {
    section: '4.1 SKB report',
    item: {
      id: 'sena', type: 'report',
      author: [
        { family: 'Sena', given: 'C' }, { family: 'Grandia', given: 'F' },
        { family: 'Arcos', given: 'D' }, { family: 'Molinero', given: 'J' },
        { family: 'Duro', given: 'L' }],
      issued: { 'date-parts': [[2008]] },
      title: 'Complementary modelling of radionuclide retention in the near-surface system at Forsmark. Development of a reactive transport model using Forsmark 1.2 data',
      number: 'SKB R-08-107',
      publisher: 'Svensk Kärnbränslehantering AB',
    },
    expected: 'Sena C, Grandia F, Arcos D, Molinero J, Duro L, 2008. Complementary modelling of radionuclide retention in the near-surface system at Forsmark. Development of a reactive transport model using Forsmark 1.2 data. SKB R-08-107, Svensk Kärnbränslehantering AB.',
    citation: 'Sena et al. (2008)', citationMode: 'author-only',
  },
  {
    section: '4.1 SKB report, institution as author',
    item: {
      id: 'skb2003', type: 'report',
      author: [{ literal: 'SKB' }],
      issued: { 'date-parts': [[2003]] },
      title: 'Planning report for the safety assessment SR-Can',
      number: 'SKB TR-03-08',
      publisher: 'Svensk Kärnbränslehantering AB',
    },
    expected: 'SKB, 2003. Planning report for the safety assessment SR-Can. SKB TR-03-08, Svensk Kärnbränslehantering AB.',
    citation: '(SKB 2003)',
  },
  {
    section: '4.1 Information material',
    item: {
      id: 'skb2008', type: 'report',
      author: [{ literal: 'SKB' }],
      issued: { 'date-parts': [[2008]] },
      title: 'Encapsulation – when, where, how and why?',
      publisher: 'Svensk Kärnbränslehantering AB',
    },
    expected: 'SKB, 2008. Encapsulation – when, where, how and why? Svensk Kärnbränslehantering AB.',
    citation: '(SKB 2008)',
  },
  {
    section: '4.1 SKBdoc document',
    item: {
      id: 'leskinen', type: 'report',
      author: [{ family: 'Leskinen', given: 'N' }, { family: 'Ronneteg', given: 'U' }],
      issued: { 'date-parts': [[2011]] },
      title: 'Tillverkning av kapselkomponenter',
      number: 'SKBdoc 1175208 ver 5.0',
      publisher: 'Svensk Kärnbränslehantering AB',
      language: 'sv',
    },
    expected: 'Leskinen N, Ronneteg U, 2011. Tillverkning av kapselkomponenter. SKBdoc 1175208 ver 5.0, Svensk Kärnbränslehantering AB. (In Swedish.)',
    citation: '(Leskinen and Ronneteg 2011)',
  },
  {
    section: '4.2 Report from another organisation',
    item: {
      id: 'nagra', type: 'report',
      author: [{ literal: 'Nagra' }],
      issued: { 'date-parts': [[2002]] },
      title: 'Project Opalinus Clay. Safety Report. Demonstration of disposal feasibility for spent fuel, vitrified high-level waste and long-lived intermediate-level waste (Entsorgungsnachweis)',
      number: 'Nagra Technical Report 02-05',
      publisher: 'National Cooperative for the Disposal of Radioactive Waste',
      'publisher-place': 'Switzerland',
    },
    expected: 'Nagra, 2002. Project Opalinus Clay. Safety Report. Demonstration of disposal feasibility for spent fuel, vitrified high-level waste and long-lived intermediate-level waste (Entsorgungsnachweis). Nagra Technical Report 02-05, National Cooperative for the Disposal of Radioactive Waste, Switzerland.',
    citation: '(Nagra 2002)',
  },
  {
    section: '4.3 Thesis',
    item: {
      id: 'bugmann', type: 'thesis',
      author: [{ family: 'Bugmann', given: 'H K M' }],
      issued: { 'date-parts': [[1994]] },
      title: 'On the ecology of mountainous forest in a changing climate: a simulation study',
      genre: 'PhD thesis',
      publisher: 'Swiss Federal Institute of Technology',
    },
    expected: 'Bugmann H K M, 1994. On the ecology of mountainous forest in a changing climate: a simulation study. PhD thesis. Swiss Federal Institute of Technology.',
    citation: 'Bugmann (1994)', citationMode: 'author-only',
  },
  {
    section: '4.4 Journal article',
    item: {
      id: 'akagawa', type: 'article-journal',
      author: [
        { family: 'Akagawa', given: 'F' }, { family: 'Yoshida', given: 'H' },
        { family: 'Yogo', given: 'S' }, { family: 'Yamomoto', given: 'K' }],
      issued: { 'date-parts': [[2006]] },
      title: 'Redox front formation in fractured crystalline rock: an analogue of matrix diffusion in an oxidizing front along water-conducting fractures',
      'container-title': 'Geochemistry: Exploration, Environment, Analysis',
      volume: '6', page: '49-56',
    },
    expected: 'Akagawa F, Yoshida H, Yogo S, Yamomoto K, 2006. Redox front formation in fractured crystalline rock: an analogue of matrix diffusion in an oxidizing front along water-conducting fractures. Geochemistry: Exploration, Environment, Analysis 6, 49–56.',
    citation: 'Akagawa et al. (2006)', citationMode: 'author-only',
  },
  {
    section: '4.4 Electronic journal article with doi',
    item: {
      id: 'vanderveen', type: 'article-journal',
      author: [{ family: 'van der Veen', given: 'C J' }],
      issued: { 'date-parts': [[2007]] },
      title: 'Fracture propagation as means of rapidly transferring surface meltwater to the base of glaciers',
      'container-title': 'Geophysical Research Letters',
      volume: '34', page: 'L01501',
      DOI: '10.1029/2006GL028385',
    },
    expected: 'van der Veen C J, 2007. Fracture propagation as means of rapidly transferring surface meltwater to the base of glaciers. Geophysical Research Letters 34, L01501. https://doi.org/10.1029/2006GL028385',
    citation: '(van der Veen 2007)',
  },
  {
    section: '4.4 Newspaper article',
    item: {
      id: 'keller', type: 'article-newspaper',
      author: [{ family: 'Keller', given: 'B' }],
      issued: { 'date-parts': [[2002, 5, 26]] },
      title: 'Nuclear nightmares',
      'container-title': 'The New York Times',
      page: '6',
    },
    expected: 'Keller B, 2002. Nuclear nightmares. The New York Times, 26 May, 6.',
    citation: 'Keller (2002)', citationMode: 'author-only',
  },
  {
    section: '4.5 Conference paper',
    item: {
      id: 'bardet', type: 'paper-conference',
      author: [
        { family: 'Bardet', given: 'J P' }, { family: 'Huang', given: 'Q' },
        { family: 'Proubet', given: 'J' }],
      issued: { 'date-parts': [[1992]] },
      title: 'A micromechanical investigation of the influence of couple stresses on failure in granular materials',
      editor: [{ family: 'Tillerson', given: 'J A' }, { family: 'Wawersik', given: 'W R' }],
      'container-title': 'Proceedings of the 33rd U.S. Symposium on Rock Mechanics, Santa Fe, New Mexico, 3–5 June 1992',
      'publisher-place': 'Rotterdam', publisher: 'Balkema', page: '609-617',
    },
    expected: 'Bardet J P, Huang Q, Proubet J, 1992. A micromechanical investigation of the influence of couple stresses on failure in granular materials. In Tillerson J A, Wawersik W R (eds). Proceedings of the 33rd U.S. Symposium on Rock Mechanics, Santa Fe, New Mexico, 3–5 June 1992. Rotterdam: Balkema, 609–617.',
    citation: 'Bardet et al. (1992)', citationMode: 'author-only',
  },
  {
    section: '4.6 Book, one author',
    item: {
      id: 'geschwind', type: 'book',
      author: [{ family: 'Geschwind', given: 'C-H' }],
      issued: { 'date-parts': [[2001]] },
      title: 'California earthquakes: science, risk, & the politics of hazard mitigation',
      'publisher-place': 'Baltimore, MD', publisher: 'Johns Hopkins University Press',
    },
    expected: 'Geschwind C-H, 2001. California earthquakes: science, risk, & the politics of hazard mitigation. Baltimore, MD: Johns Hopkins University Press.',
    citation: 'Geschwind (2001)', citationMode: 'author-only',
  },
  {
    section: '4.6 Book, two authors, edition',
    item: {
      id: 'wyllie', type: 'book',
      author: [{ family: 'Wyllie', given: 'D C' }, { family: 'Mah', given: 'C W' }],
      issued: { 'date-parts': [[2004]] },
      title: 'Rock slope engineering: civil and mining',
      edition: '4',
      'publisher-place': 'New York', publisher: 'Spon Press',
    },
    expected: 'Wyllie D C, Mah C W, 2004. Rock slope engineering: civil and mining. 4th ed. New York: Spon Press.',
    citation: '(Wyllie and Mah 2004)',
  },
  {
    section: '4.6 Book, editor',
    item: {
      id: 'jenne', type: 'book',
      editor: [{ family: 'Jenne', given: 'E A' }],
      issued: { 'date-parts': [[1998]] },
      title: 'Adsorption of metals by geomedia: variables, mechanisms, and model applications',
      'publisher-place': 'San Diego, CA', publisher: 'Academic Press',
    },
    expected: 'Jenne E A (ed), 1998. Adsorption of metals by geomedia: variables, mechanisms, and model applications. San Diego, CA: Academic Press.',
    citation: '(Jenne 1998)',
  },
  {
    section: '4.6 Book, two editors',
    item: {
      id: 'storch', type: 'book',
      editor: [{ family: 'von Storch', given: 'H', 'non-dropping-particle': '' }, { family: 'Flöser', given: 'G' }],
      issued: { 'date-parts': [[1999]] },
      title: 'Anthropogenic climate change',
      'publisher-place': 'Berlin', publisher: 'Springer',
    },
    expected: 'von Storch H, Flöser G (eds), 1999. Anthropogenic climate change. Berlin: Springer.',
    citation: 'von Storch and Flöser (1999)', citationMode: 'author-only',
  },
  {
    section: '4.6 Corporate author',
    item: {
      id: 'mit', type: 'book',
      author: [{ literal: 'MIT' }],
      issued: { 'date-parts': [[2003]] },
      title: 'The future of nuclear power: an interdisciplinary MIT study',
      'publisher-place': 'Boston, MA', publisher: 'Massachusetts Institute of Technology',
    },
    expected: 'MIT, 2003. The future of nuclear power: an interdisciplinary MIT study. Boston, MA: Massachusetts Institute of Technology.',
    citation: 'MIT (2003)', citationMode: 'author-only',
  },
  {
    section: '4.6 Author unknown',
    item: {
      id: 'merriam', type: 'book',
      issued: { 'date-parts': [[1993]] },
      title: "Merriam-Webster's collegiate dictionary",
      edition: '10',
      'publisher-place': 'Springfield, MA', publisher: 'Merriam-Webster',
    },
    expected: "Merriam-Webster's collegiate dictionary, 1993. 10th ed. Springfield, MA: Merriam-Webster.",
    citation: "(Merriam-Webster's collegiate dictionary 1993)",
  },
  {
    section: '4.7 Volume of a multivolume work',
    item: {
      id: 'brown', type: 'book',
      author: [{ family: 'Brown', given: 'C L' }],
      issued: { 'date-parts': [[2003]] },
      title: 'Thermodynamics',
      volume: '2', edition: '2',
      'publisher-place': 'New York', publisher: 'McGraw-Hill',
    },
    expected: 'Brown C L, 2003. Thermodynamics. Vol 2. 2nd ed. New York: McGraw-Hill.',
    citation: 'Brown (2003)', citationMode: 'author-only',
  },
  {
    section: '4.8 Chapter in an edited work',
    item: {
      id: 'saugier', type: 'chapter',
      author: [{ family: 'Saugier', given: 'B' }, { family: 'Roy', given: 'R' }, { family: 'Mooney', given: 'H A' }],
      issued: { 'date-parts': [[2001]] },
      title: 'Estimations of global terrestrial productivity: converging toward a single number?',
      editor: [{ family: 'Roy', given: 'J' }, { family: 'Saugier', given: 'B' }, { family: 'Mooney', given: 'H A' }],
      'container-title': 'Terrestrial global productivity',
      'publisher-place': 'London', publisher: 'Academic Press', page: '543-557',
    },
    expected: 'Saugier B, Roy R, Mooney H A, 2001. Estimations of global terrestrial productivity: converging toward a single number? In Roy J, Saugier B, Mooney H A (eds). Terrestrial global productivity. London: Academic Press, 543–557.',
    citation: '(Saugier et al. 2001)',
  },
  {
    section: '4.9 Publication in a series',
    item: {
      id: 'garcia', type: 'book',
      author: [{ family: 'García Ambrosiani', given: 'K' }],
      issued: { 'date-parts': [[1990]] },
      title: 'Pleistocene stratigraphy in central and northern Sweden: a reinvestigation of some classical sites',
      'publisher-place': 'Stockholm', publisher: 'Stockholm University',
      'collection-title': 'Reports of Department of Quaternary Research',
      'collection-number': '16',
    },
    expected: 'García Ambrosiani K, 1990. Pleistocene stratigraphy in central and northern Sweden: a reinvestigation of some classical sites. Stockholm: Stockholm University. (Reports of Department of Quaternary Research 16)',
    citation: 'García Ambrosiani (1990)', citationMode: 'author-only',
  },
  {
    section: '4.10 Standard, institution as main entry',
    item: {
      id: 'bsi', type: 'standard',
      author: [{ literal: 'BSI' }],
      issued: { 'date-parts': [[2008]] },
      title: 'BS ISO 81782: Reciprocating internal combustion engines – Exhaust emission measurement',
      'publisher-place': 'London', publisher: 'British Standards Institute',
    },
    expected: 'BSI, 2008. BS ISO 81782: Reciprocating internal combustion engines – Exhaust emission measurement. London: British Standards Institute.',
    citation: '(BSI 2008)',
  },
  {
    section: '4.10 Standard, designation as main entry',
    item: {
      id: 'ssen', type: 'standard',
      number: 'SS-EN 1936:1999',
      title: 'Natural stone test methods: determination of real density and apparent density, and of total and open porosity',
      'publisher-place': 'Stockholm', publisher: 'Swedish Standards Institute',
    },
    expected: 'SS-EN 1936:1999. Natural stone test methods: determination of real density and apparent density, and of total and open porosity. Stockholm: Swedish Standards Institute.',
    citation: '(SS-EN 1936:1999)',
  },
  {
    section: '4.11 Government publication, designation as main entry',
    item: {
      id: 'ds', type: 'legislation',
      number: 'Ds 2007:30',
      title: "Sweden's fourth national report under the Convention on Nuclear Safety",
      'publisher-place': 'Stockholm', publisher: 'Ministry of the Environment',
    },
    expected: "Ds 2007:30. Sweden's fourth national report under the Convention on Nuclear Safety. Stockholm: Ministry of the Environment.",
    citation: '(Ds 2007:30)',
  },
  {
    section: '4.12 Swedish act',
    item: {
      id: 'sfs', type: 'legislation',
      number: 'SFS 1984:3',
      title: 'Lag om kärnteknisk verksamhet',
      'publisher-place': 'Stockholm', publisher: 'Riksdagen',
      /*
        Language deliberately left empty. The instruction is inconsistent
        here: it prints SFS 1984:3 with no language note but SSMFS 2008:21
        with "(In Swedish.)". The style adds the note whenever the Language
        field is filled in, so the author decides per reference.
      */
    },
    expected: 'SFS 1984:3. Lag om kärnteknisk verksamhet. Stockholm: Riksdagen.',
    citation: '(SFS 1984:3)',
  },
  {
    section: '4.13 WWW page with corporate author',
    item: {
      id: 'iucn', type: 'webpage',
      author: [{ literal: 'IUCN' }],
      issued: { 'date-parts': [[2011]] },
      title: 'The IUCN red list of threatened species. Version 2011.1',
      URL: 'http://www.iucnredlist.org/',
      accessed: { 'date-parts': [[2011, 9, 24]] },
    },
    expected: 'IUCN, 2011. The IUCN red list of threatened species. Version 2011.1. Available at: http://www.iucnredlist.org/ [24 September 2011].',
    citation: '(IUCN 2011)',
  },
  {
    section: '4.13 WWW page without a date',
    item: {
      id: 'dof', type: 'webpage',
      author: [{ literal: 'DOF' }],
      title: 'Natur og fugle. Dansk Ornitologisk Forening',
      URL: 'http://www.dofbasen.dk/ART/',
      accessed: { 'date-parts': [[2011, 8, 15]] },
      language: 'da',
    },
    expected: 'DOF, n d. Natur og fugle. Dansk Ornitologisk Forening. Available at: http://www.dofbasen.dk/ART/ [15 August 2011]. (In Danish.)',
    citation: '(DOF, n d)',
  },
  {
    section: '4.13 Newspaper article online',
    item: {
      id: 'cooke', type: 'article-newspaper',
      author: [{ family: 'Cooke', given: 'S' }],
      issued: { 'date-parts': [[2009, 3, 17]] },
      title: 'A nuclear waste',
      'container-title': 'The New York Times',
      URL: 'http://www.nytimes.com/2009/03/18/opinion/18cooke.html',
      accessed: { 'date-parts': [[2009, 5, 12]] },
    },
    expected: 'Cooke S, 2009. A nuclear waste. The New York Times, 17 March. Available at: http://www.nytimes.com/2009/03/18/opinion/18cooke.html [12 May 2009].',
    citation: 'Cooke (2009)', citationMode: 'author-only',
  },
  {
    section: '4.14 Computer software',
    item: {
      id: 'itasca', type: 'software',
      author: [{ literal: 'Itasca' }],
      issued: { 'date-parts': [[2007]] },
      title: '3DEC – 3-dimensional distinct element code, version 4.1',
      'publisher-place': 'Minneapolis, MN', publisher: 'Itasca Consulting Group, Inc.',
    },
    expected: 'Itasca, 2007. 3DEC – 3-dimensional distinct element code, version 4.1. Minneapolis, MN: Itasca Consulting Group, Inc.',
    citation: '(Itasca 2007)',
  },
];
