/* ==========================================================================
   RTM.HTML: THE BUILT-IN MODEL

   Generated by scripts/gen-rtm-default.py from the skbrtm example databases;
   edit those, or the script, rather than this file.
   ========================================================================== */
const RTM_DEFAULT_MODEL = `# ============================================================================
#  WATER RADIOLYSIS AND URANIUM DISSOLUTION AT A SPENT-FUEL SURFACE
#
#  119 reactions over 36 species, from the skbrtm example set
#  (examples/transport/PA_BRUM_test). The left-hand boundary is the fuel
#  surface; the domain is the thin film of water in front of it.
#
#  Set MODE = batch to ignore the film and stir everything together, which is
#  much quicker and is the right first look at a reaction set.
# ============================================================================

<SETTINGS>
MODE      = transport      # batch | transport
CELLS     = 20             # cells across the film
LENGTH    = 2.0E-4         # m, the thickness of the film
GRID      = linear         # linear | log (log packs cells against the surface)
DIFFUSION = 1
ADVECTION = 0
VELOCITY  = 0              # m/s, positive is left to right
LEFT      = dirichlet      # the bulk water holds its composition
RIGHT     = neumann        # nothing crosses the far face
TEND      = 1.0E5          # s

<SPECIES>
# name        initial     fixed | D = m2/s | left = , right = boundary values
H2O       55.56       fixed
H+        1.00e-7     D=1e-09  left=1.00e-7
OH-       1.00e-7     D=1e-09  left=1.00e-7
HCO3-     2.00e-3     fixed
alpha     1.          fixed
U_site    5.25e-3
E_site    5.25e-5
H2        8e-4        D=1e-09  left=8e-4
e-        0.0         D=1e-09
Hr        0.0         D=1e-09
OHr       0.0         D=1e-09
O-        0.0         D=1e-09
H2O2      0.0         D=1e-09
HO2-      0.0         D=1e-09
HO2r      0.0         D=1e-09
O2        0.0         D=1e-09
O2-       0.0         D=1e-09
O3-       0.0         D=1e-09
O3        0.0         D=1e-09
HO3       0.0         D=1e-09
CO2       0.0         D=1e-09
CO3-2     0.0         D=1e-09
CO2-      0.0         D=1e-09
CO3-      0.0         D=1e-09
C2O6-2    0.0         D=1e-09
C2O4-2    0.0         D=1e-09
HCOO-     0.0         D=1e-09
C2O4-     0.0         D=1e-09
OHra      0.0         D=1e-09
UVO2s+    0.0
UVIO2s+2  0.0
UO2CO3    0.0         D=1e-09
ox        0.0
red       0.0
O2-2      0.0         D=1e-09
ox2       0.0         D=1e-09

<REACTIONS>
# stoichiometry, then the rate: k = ... for mass action, or r = ... for a law
# of your own with its parameters after it. A concentration is written [name].

# Radiolysis: nothing on the left is a source, here G (mol/J) times the alpha
# dose rate (Gy/s). Set DOSE = 0 on these lines to switch the radiation off.
=> e-, k = G*DOSE, G = 1.6e-08, DOSE = 0.64
=> Hr, k = G*DOSE, G = 1e-08, DOSE = 0.64
=> H2, k = G*DOSE, G = 1.2e-07, DOSE = 0.64
=> OHr, k = G*DOSE, G = 3.6e-08, DOSE = 0.64
=> H2O2, k = G*DOSE, G = 1e-07, DOSE = 0.64
=> HO2r, k = G*DOSE, G = 1e-08, DOSE = 0.64
=> H+, k = G*DOSE, G = 1.9e-08, DOSE = 0.64
=> OH-, k = G*DOSE, G = 3e-09, DOSE = 0.64

e- + H2O => Hr + OH-, r = k*[e-]*[H2O], k = 1.9e1
e- + e- + H2O + H2O => H2 + OH- + OH-, r = k*[e-]**2*[H2O]**2, k = 1.8e6
e- + Hr + H2O => H2 + OH-, r = k*[e-]*[Hr]*[H2O], k = 4.5e8
e- + OHr => OH-, r = k*[e-]*[OHr], k = 3.0e10
e- + O- + H2O => OH- + OH-, r = k*[e-]*[O-]*[H2O], k = 4.0e8
e- + H+ => Hr, r = k*[e-]*[H+], k = 2.3e10
e- + H2O2 => OHr + OH-, r = k*[e-]*[H2O2], k = 1.1e10
e- + HO2- => O- + OH-, r = k*[e-]*[HO2-], k = 3.5e9
e- + HO2r => HO2-, r = k*[e-]*[HO2r], k = 2.0e10
e- + O2 => O2-, r = k*[e-]*[O2], k = 1.9e10
e- + O2- + H2O => HO2- + OH-, r = k*[e-]*[O2-]*[H2O], k = 2.3e8
e- + O3- + H2O => OH- + OH- + O2, r = k*[e-]*[O3-]*[H2O], k = 2.9e8
e- + O3 => O3-, r = k*[e-]*[O3], k = 3.6e10
Hr + H2O => H2 + OHr, r = k*[Hr]*[H2O], k = 1.1e1
Hr + Hr => H2, r = k*[Hr]**2, k = 7.8e9
Hr + OHr => H2O, r = k*[Hr]*[OHr], k = 7.0e9
Hr + OH- => e- + H2O, r = k*[Hr]*[OH-], k = 2.2e7
Hr + H2O2 => H2O + OHr, r = k*[Hr]*[H2O2], k = 9.0e7
Hr + O2 => HO2r, r = k*[Hr]*[O2], k = 2.1e10
Hr + O2- => HO2-, r = k*[Hr]*[O2-], k = 1.8e10
Hr + HO2r => H2O2, r = k*[Hr]*[HO2r], k = 1.8e10
Hr + HO2- => OHr + OH-, r = k*[Hr]*[HO2-], k = 9.0e7
Hr + O- => OH-, r = k*[Hr]*[O-], k = 1.0e10
Hr + O3- => OH- + O2, r = k*[Hr]*[O3-], k = 1.0e10
Hr + O3 => HO3, r = k*[Hr]*[O3], k = 3.8e10
Hr => e- + H+, r = k*[Hr], k = 3.9e0
OHr + OHr => H2O2, r = k*[OHr]**2, k = 3.6e9
OHr + O- => HO2-, r = k*[OHr]*[O-], k = 2.5e10
OHr + H2 => Hr + H2O, r = k*[OHr]*[H2], k = 4.3e7
OHr + OH- => O- + H2O, r = k*[OHr]*[OH-], k = 1.3e10
OHr + H2O2 => HO2r + H2O, r = k*[OHr]*[H2O2], k = 2.7e7
OHr + HO2- => HO2r + OH-, r = k*[OHr]*[HO2-], k = 7.5e9
OHr + HO2r => H2O + O2, r = k*[OHr]*[HO2r], k = 6.0e9
OHr + O2- => OH- + O2, r = k*[OHr]*[O2-], k = 8.2e9
OHr => O- + H+, r = k*[OHr], k = 1.3e-1
OHr + O3- => O3 + OH-, r = k*[OHr]*[O3-], k = 2.6e9
OHr + O3- => O2- + O2- + H+, r = k*[OHr]*[O3-], k = 6.0e9
OHr + O3 => HO2r + O2, r = k*[OHr]*[O3], k = 1.1e8
O- + H2O => OHr + OH-, r = k*[O-]*[H2O], k = 1.9e6
O- + O- + H2O => HO2- + OH-, r = k*[O-]*[O-]*[H2O], k = 1.8e7
O- + H2 => Hr + OH-, r = k*[O-]*[H2], k = 8.0e7
O- + H2O2 => O2- + H2O, r = k*[O-]*[H2O2], k = 5.0e8
O- + HO2- => O2- + OH-, r = k*[O-]*[HO2-], k = 4.0e8
O- + O2 => O3-, r = k*[O-]*[O2], k = 3.6e9
O- + H+ => OHr, r = k*[O-]*[H+], k = 1.0e11
O- + O3- => O2- + O2-, r = k*[O-]*[O3-], k = 7.0e8
O- + O3 => O2- + O2, r = k*[O-]*[O3], k = 5.0e9
O2- + O- + H2O => O2 + OH- + OH-, r = k*[O2-]*[O-]*[H2O], k = 1.1e7
O2- + O2- + H2O + H2O => H2O2 + O2 + OH- + OH-, r = k*[O2-]**2*[H2O]**2, k = 3.2e-2
O2- + H2O2 => OHr + O2 + OH-, r = k*[O2-]*[H2O2], k = 1.3e-1
O2- + HO2- => O- + O2 + OH-, r = k*[O2-]*[HO2-], k = 1.3e-1
O2- + O3- + H2O => O2 + O2 + OH- + OH-, r = k*[O2-]*[O3-]*[H2O], k = 1.8e2
O2- + O3 => O3- + O2, r = k*[O2-]*[O3], k = 1.5e9
O2- + H+ => HO2r, r = k*[O2-]*[H+], k = 5.0e10
O2- + H2O => HO2r + OH-, r = k*[O2-]*[H2O], k = 3.4e-1
O3- => O2 + O-, r = k*[O3-], k = 3.3e3
O3- + H+ => O2 + OHr, r = k*[O3-]*[H+], k = 9.0e10
H+ + HO2- => H2O2, r = k*[H+]*[HO2-], k = 5.0e10
H+ + OH- => H2O, r = k*[H+]*[OH-], k = 1.4e11
H2O => H+ + OH-, r = k*[H2O], k = 2.5e-5
HO2- + H2O => OH- + H2O2, r = k*[HO2-]*[H2O], k = 1.0e6
HO2r => O2- + H+, r = k*[HO2r], k = 1.3e6
HO2r + OH- => O2- + H2O, r = k*[HO2r]*[OH-], k = 5.0e10
HO2r + O2- => HO2- + O2, r = k*[HO2r]*[O2-], k = 8.0e7
HO2r + HO2r => H2O2 + O2, r = k*[HO2r]**2, k = 7.0e5
HO2r + O- => O2 + OH-, r = k*[HO2r]*[O-], k = 6.0e9
HO2r + H2O2 => OHr + O2 + H2O, r = k*[HO2r]*[H2O2], k = 5.0e-1
HO2r + HO2- => OHr + O2 + OH-, r = k*[HO2r]*[HO2-], k = 5.0e-1
HO2r + O3- => O2 + O2 + OH-, r = k*[HO2r]*[O3-], k = 6.0e9
HO2r + O3 => HO3 + O2, r = k*[HO2r]*[O3], k = 5.0e8
HO3 => O2 + OHr, r = k*[HO3], k = 1.1e5
H2O2 => H+ + HO2-, r = k*[H2O2], k = 1.1e-1
H2O2 + OH- => HO2- + H2O, r = k*[H2O2]*[OH-], k = 1.3e10
CO2 + H2O => HCO3- + H+, r = k*[CO2]*[H2O], k = 2.0e4
HCO3- + H+ => CO2 + H2O, r = k*[HCO3-]*[H+], k = 5.0e10
HCO3- => CO3-2 + H+, r = k*[HCO3-], k = 2.0e0
CO3-2 + H+ => HCO3-, r = k*[CO3-2]*[H+], k = 5.0e10
CO2 + e- => CO2-, r = k*[CO2]*[e-], k = 7.7e9
CO3-2 + e- + H2O => CO2- + OH- + OH-, r = k*[CO3-2]*[e-]*[H2O], k = 3.9e5
HCO3- + Hr => CO3- + H2, r = k*[HCO3-]*[Hr], k = 4.4e4
HCO3- + OHr => CO3- + H2O, r = k*[HCO3-]*[OHr], k = 8.5e6
CO3-2 + OHr => CO3- + OH-, r = k*[CO3-2]*[OHr], k = 3.9e8
CO3- + CO3- => C2O6-2, r = k*[CO3-]**2, k = 1.4e7
C2O6-2 => C2O4-2 + O2, r = k*[C2O6-2], k = 1.0e0
C2O6-2 + H2O => HO2- + OH- + CO2 + CO2, r = k*[C2O6-2]*[H2O], k = 2.0e2
CO3- + H2O2 => CO3-2 + O2- + H+ + H+, r = k*[CO3-]*[H2O2], k = 9.8e5
CO3- + HO2- => CO3-2 + O2- + H+, r = k*[CO3-]*[HO2-], k = 1.0e7
CO3- + O2- => CO3-2 + O2, r = k*[CO3-]*[O2-], k = 4.0e8
CO3- + CO2- => CO3-2 + CO2, r = k*[CO3-]*[CO2-], k = 3.0e8
CO2- + e- => HCOO- + OH-, r = k*[CO2-]*[e-], k = 9.0e8
CO2- + CO2- => C2O4-2, r = k*[CO2-]**2, k = 6.5e8
CO2- + H2O2 => CO2 + OHr + OH-, r = k*[CO2-]*[H2O2], k = 7.3e5
CO2- + HCO3- => CO3- + HCOO-, r = k*[CO2-]*[HCO3-], k = 1.0e3
CO3- + HCOO- => HCO3- + CO2-, r = k*[CO3-]*[HCOO-], k = 1.5e5
OHr + HCOO- => CO2- + H2O, r = k*[OHr]*[HCOO-], k = 3.2e9
Hr + HCOO- => CO2- + H2, r = k*[Hr]*[HCOO-], k = 2.1e8
e- + HCOO- + H+ => CO2- + H2, r = k*[e-]*[HCOO-]*[H+], k = 8.0e3
OHr + C2O4-2 => CO2- + CO2 + OH-, r = k*[OHr]*[C2O4-2], k = 4.0e7
CO2- + O2 => CO2 + O2-, r = k*[CO2-]*[O2], k = 2.0e9
CO3- + C2O4-2 => C2O4- + CO3-2, r = k*[CO3-]*[C2O4-2], k = 3.0e3
H2O2 + U_site => OHra + OHra, r = k*[H2O2]*[U_site], k = 0.462
OHra => OH- + UVO2s+, r = k*[OHra], k = 0.191
H2O2 + OHra => HO2r + H2O + 0.5U_site, r = k*[H2O2]*[OHra], k = 197.0
UVO2s+ + UVO2s+ => UVIO2s+2 + 0.5U_site, r = k*[UVO2s+]**2, k = 34.1
HCO3- + UVIO2s+2 => H+ + UO2CO3 + 0.5U_site, r = k*[HCO3-]*[UVIO2s+2], k = 1.0e3
H2O2 + E_site => ox, r = k*[H2O2]*[E_site], k = 46.2
ox + U_site => UVIO2s+2 + E_site + 2OH- + 0.5U_site, r = k*[ox]*[U_site], k = 1.0e16
OHra + H2 => Hr + 0.5U_site + H2O, r = k*[OHra]*[H2], k = 75.0
E_site + H2 => red, r = k*[E_site]*[H2], k = 1.0e3
red + UVIO2s+2 => 0.5U_site + H+ + H+ + E_site, r = k*[red]*[UVIO2s+2], k = 1.0e16
O2 + U_site => O2-2 + UVIO2s+2 + 0.5U_site, r = k*[O2]*[U_site], k = 2.31e-3
O2-2 + H+ + H+ => H2O2, r = k*[O2-2]*[H+]**2, k = 1.0e16
O2 + E_site => ox2, r = k*[O2]*[E_site], k = 0.77
ox2 + U_site => UVIO2s+2 + E_site + O2-2 + 0.5U_site, r = k*[ox2]*[U_site], k = 1.0e16
H2O2 + E_site => H2O + 0.5O2 + E_site, r = k*[H2O2]*[E_site], k = 23.6
H2O2 + H2 + E_site => H2O + H2O + E_site, r = k*[H2O2]*[E_site], k = 114.0
UO2CO3 + H2 + E_site => H+ + H+ + E_site, r = k*[UO2CO3]*[E_site], k = 71.4
OHr + U_site => OHra + 0.5U_site, r = k*[OHr]*[U_site], k = 2.0e3
CO3- + U_site => UVO2s+ + CO3-2 + 0.5U_site, r = k*[CO3-]*[U_site], k = 2.0e3

<INITIAL>
# species  cells  value     -- overrides the concentration above, per cell
`;

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { RTM_DEFAULT_MODEL };
}
