name = "Kompartment"
uuid = "b7afe032-4cb8-4f97-bed6-263595b81919"
version = "0.1.0"
authors = ["Kvot AB"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FunctionWrappers = "069b7b12-0de2-55c6-9aab-29f3d0a68a2e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SuiteSparse_jll = "bea87d4a-7f5b-5778-9afe-8cc45184846c"
Zlib_jll = "83775a58-1f1d-513f-b197-d71354ab007a"

[weakdeps]
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[extensions]
KompartmentOrdinaryDiffEqExt = "OrdinaryDiffEq"
KompartmentTablesExt = "Tables"

[compat]
OrdinaryDiffEq = "6.90, 7"
Dates = "1"
FunctionWrappers = "1"
LinearAlgebra = "1"
OrderedCollections = "1, 2"
PrecompileTools = "1"
Printf = "1"
SHA = "0.7, 1"
SparseArrays = "1"
SuiteSparse_jll = "5, 7"
Tables = "1"
Zlib_jll = "1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
