"""Click the theme toggle on every page and check the theme actually changes.

The previous action-dispatch test enumerated the elements that carried a
data-on-* attribute and proved each reached its handler. The two buttons the
site chrome generates carried the superseded data-action name, so they were
never in the inventory: a test that enumerates what exists cannot see what is
missing. This one starts from the button, not from the attribute.
"""
import asyncio, json, sys, time, urllib.request, websockets

PAGES = ['index.html', 'proj.html', 'rb.html', 'rdc.html', 'logn.html',
         'karaoke.html', 'skbref.html', 'skb_qa_summary.html', 'uppsala.html',
         'solna.html', 'kompartment.html', 'ensdf.html', 'zoterify.html', '404.html']

PROBE = r"""(async () => {
  const button = document.querySelector('button.theme-toggle');
  if (!button) return JSON.stringify({ error: 'no .theme-toggle button' });

  const root = document.documentElement;
  const before = root.getAttribute('data-theme');
  const beforeIcon = button.textContent.trim();
  const beforeBg = getComputedStyle(document.body).backgroundColor;

  button.click();
  await new Promise(r => setTimeout(r, 120));

  const after = root.getAttribute('data-theme');
  const afterIcon = button.textContent.trim();
  const afterBg = getComputedStyle(document.body).backgroundColor;

  /* And the office-map button, generated by the same code path. */
  const mapButton = document.querySelector('button.icon-btn[data-on-click="kvot:toggleMap"], button.icon-btn[data-action="kvot:toggleMap"]');
  let mapWired = null;
  if (mapButton) {
    const map = document.getElementById('kvotmap');
    /* toggleMap flips inline visibility rather than a class. */
    const mapBefore = map ? map.style.visibility : null;
    mapButton.click();
    await new Promise(r => setTimeout(r, 150));
    mapWired = map ? (map.style.visibility !== mapBefore && map.style.visibility === 'visible') : 'no #kvotmap';
  }

  /* No element anywhere may still use the superseded attribute names, except
     karaoke's own local convention, which binds its rows directly. */
  const stale = [...document.querySelectorAll('[data-action], [data-action-on]')]
    .filter(el => !/^(up|down|setnow|addbelow|remove)$/.test(el.getAttribute('data-action') || ''))
    .map(el => el.tagName.toLowerCase() + '[' + (el.getAttribute('data-action') || el.getAttribute('data-action-on')) + ']');

  return JSON.stringify({
    themeChanged: before !== after,
    before, after, beforeIcon, afterIcon,
    backgroundChanged: beforeBg !== afterBg,
    mapWired, stale
  });
})()"""


async def check(bws, page):
    stamp = int(time.time() * 1000)
    await bws.send(json.dumps({'id': 1, 'method': 'Target.createTarget',
                               'params': {'url': 'http://127.0.0.1:8765/%s?nocache=%d' % (page, stamp)}}))
    tid = None
    while tid is None:
        m = json.loads(await bws.recv())
        if m.get('id') == 1: tid = m['result']['targetId']
    await bws.send(json.dumps({'id': 2, 'method': 'Target.attachToTarget',
                               'params': {'targetId': tid, 'flatten': True}}))
    session = None
    while session is None:
        m = json.loads(await bws.recv())
        if m.get('id') == 2: session = m['result']['sessionId']
    # A desktop viewport, explicitly: uppsala.html and solna.html hide the site
    # header and footer below 560px, and the theme toggle lives in the footer.
    # Left to the ambient window size, a narrow one would make .click() land on
    # a display:none element and report the button dead when it is merely out
    # of season.
    await bws.send(json.dumps({'id': 19, 'method': 'Emulation.setDeviceMetricsOverride',
                               'sessionId': session,
                               'params': {'width': 1280, 'height': 900,
                                          'deviceScaleFactor': 1, 'mobile': False}}))
    await bws.send(json.dumps({'id': 20, 'method': 'Network.enable', 'sessionId': session}))
    await bws.send(json.dumps({'id': 21, 'method': 'Network.setCacheDisabled',
                               'sessionId': session, 'params': {'cacheDisabled': True}}))
    await asyncio.sleep(3)
    # The boot snippet applies the stored theme while the page loads, so the
    # key has to be cleared and the page reloaded for every page to start from
    # the same state. Clearing after load only changes what the NEXT page sees,
    # which made the observed start state alternate down the list.
    await bws.send(json.dumps({'id': 22, 'method': 'Runtime.evaluate', 'sessionId': session,
                               'params': {'expression': "try{localStorage.removeItem('kvot-theme')}catch(e){}; 'ok'",
                                          'returnByValue': True}}))
    while True:
        m = json.loads(await bws.recv())
        if m.get('id') == 22: break
    await bws.send(json.dumps({'id': 23, 'method': 'Page.enable', 'sessionId': session}))
    await bws.send(json.dumps({'id': 24, 'method': 'Page.reload', 'sessionId': session,
                               'params': {'ignoreCache': True}}))
    await asyncio.sleep(4)
    await bws.send(json.dumps({'id': 3, 'method': 'Runtime.evaluate', 'sessionId': session,
                               'params': {'expression': PROBE, 'awaitPromise': True, 'returnByValue': True}}))
    value = None
    while value is None:
        m = json.loads(await bws.recv())
        if m.get('id') == 3:
            value = m.get('result', {}).get('result', {}).get('value') or json.dumps(m)[:400]
    await bws.send(json.dumps({'id': 9, 'method': 'Target.closeTarget', 'params': {'targetId': tid}}))
    return value


async def main():
    ver = json.load(urllib.request.urlopen('http://127.0.0.1:9222/json/version'))
    failures = []
    async with websockets.connect(ver['webSocketDebuggerUrl'], max_size=100 * 1024 * 1024) as bws:
        for page in PAGES:
            raw = await check(bws, page)
            try:
                r = json.loads(raw)
            except Exception:
                print('%-22s HARNESS ERROR %s' % (page, raw[:120])); failures.append(page); continue
            ok = r.get('themeChanged') and r.get('backgroundChanged') and not r.get('stale')
            if r.get('mapWired') is False:
                ok = False
            print('%-22s theme %-5s  %s->%s  icon %s->%s  bg %-5s  map %-5s  stale %s' % (
                page, 'OK' if r.get('themeChanged') else 'DEAD',
                r.get('before'), r.get('after'), r.get('beforeIcon'), r.get('afterIcon'),
                'OK' if r.get('backgroundChanged') else 'SAME',
                str(r.get('mapWired')), r.get('stale') or '-'))
            if not ok: failures.append(page)
    print()
    print('%d/%d pages toggle correctly' % (len(PAGES) - len(failures), len(PAGES)))
    if failures:
        print('FAILING: ' + ', '.join(failures))
    sys.exit(1 if failures else 0)

asyncio.run(main())
