#!/usr/bin/env python3
"""Analyze > Fit Y by X and Specialized Modeling > Matched Pairs, the
backend (resources/py/smui/fit_y_by_x.py), through the page's dispatch and
JSON round trip, checked against statsmodels and scipy called directly and
against published values:

  - NIST StRD NoInt1 and NoInt2 (a line through the origin: Fit Special
    with the intercept held at 0) and Wampler1 and Wampler2 (degree 5
    polynomials); their data are generated by the formulas NIST gives, the
    certified values are typed in below.
  - Koenker's Engel food expenditure data (statsmodels.datasets.engel) for
    the median regression, as published with R's quantreg (81.48225,
    0.5601806).
  - The Chinese smoking and lung cancer tables of Liu (1992), as Agresti
    analyses them (statsmodels.datasets.china_smoking): Mantel-Haenszel
    odds ratio 2.174, CMH chi-square 280.14, Breslow-Day 5.20.
  - The values statsmodels' own test suite records from R and the
    literature: lawstat's brunner.munzel.test (Munzel and Hauschke 2003),
    the rate comparisons of Gu et al. (2008) and Ng et al. (2007) and R's
    exactci, PropCIs and Fagerland et al. (2015) for two proportions,
    DescTools' BreslowDayTest and mantelhaen.test, R's mcnemar.test, and
    Cochran's Q of Conover (NIST Dataplot) and SAS; JMP's documented Two
    Sample Test for Proportions example (adjusted Wald).

    python3 resources/tests/smui/test_fit_y_by_x.py
"""
import math
import sys

import numpy as np
import pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf
from scipy import stats
from scipy.interpolate import make_smoothing_spline

from backend import FAILED, Checks, call, table

check = Checks()
if 'fit_y_by_x' in FAILED:
    print('fit_y_by_x did not import:', FAILED['fit_y_by_x'])
    sys.exit(1)
rng = np.random.default_rng(20260926)


def rows_of(r, key='rows'):
    return r[key]


# ---- NIST StRD: NoInt1, NoInt2 (y = B1 x) ------------------------------------
x1 = np.arange(60.0, 71.0)
y1 = np.arange(130.0, 141.0)
tid = table({'x': x1, 'y': y1})
r = call('fitybyx.fit_special', table=tid, y='y', x='x', intercept=0)
est = {e['term']: e for e in r['estimates']['rows']}
check.near('NoInt1 B1 (certified)', est['x']['estimate'], 2.07438016528926, rel=1e-12)
check.near('NoInt1 SD of B1', est['x']['se'], 0.165289256198347e-01, rel=1e-10)
check.near('NoInt1 residual SD', r['summary']['rows'][1]['value'], 3.56753034006338, rel=1e-10)
tid = table({'x': [4.0, 5.0, 6.0], 'y': [3.0, 4.0, 4.0]})
r = call('fitybyx.fit_special', table=tid, y='y', x='x', intercept=0)
est = {e['term']: e for e in r['estimates']['rows']}
check.near('NoInt2 B1 (certified)', est['x']['estimate'], 0.727272727272727, rel=1e-12)
check.near('NoInt2 SD of B1', est['x']['se'], 0.420827318078432e-01, rel=1e-10)
check.near('NoInt2 residual SD', r['summary']['rows'][1]['value'], 0.369274472937998, rel=1e-10)

# ---- NIST StRD: Wampler1, Wampler2 (degree 5, exact fits) -----------------------
xw = np.arange(0.0, 21.0)
for name, coef in (('Wampler1', [1, 1, 1, 1, 1, 1]), ('Wampler2', [1, 0.1, 0.01, 0.001, 0.0001, 0.00001])):
    yw = sum(c * xw ** k for k, c in enumerate(coef))
    tid = table({'x': xw, 'y': yw})
    r = call('fitybyx.fit_poly', table=tid, y='y', x='x', degree=5)
    # the page centres the powers: b0 + b1 x + b2 (x-m)^2 + ... ; expand to raw powers
    m = float(xw.mean())
    b = [t['estimate'] for t in r['terms']]
    raw = np.polynomial.polynomial.Polynomial([b[0], b[1]])
    for k in range(2, 6):
        raw = raw + b[k] * np.polynomial.polynomial.Polynomial([-m, 1]) ** k
    ok = all(abs(a - c) <= 1e-6 * max(1, abs(c)) for a, c in zip(raw.coef, coef))
    check(f'{name} raw coefficients (certified) to 1e-6', ok)
    check(f'{name} term names', [t['term'] for t in r['terms']], ['Intercept', 'x'] + [f'(x-{m:.6g})^{k}' for k in range(2, 6)])
    check(f'{name} residual SD 0 (certified)', abs(r['rmse']) < 1e-6 * max(1, float(np.abs(yw).max())), True)

# ---- Bivariate: Fit Line, weights, Freq, lack of fit -------------------------------
n = 90
xb = np.round(rng.uniform(140, 185, n), 0)
yb = -60 + 0.72 * xb + rng.normal(0, 5, n)
xb[3] = np.nan
wb = rng.uniform(0.5, 2.0, n)
fb = rng.integers(1, 4, n).astype(float)
gb = rng.choice(['F', 'M'], n).tolist()
tid = table({'height': xb, 'weight': yb, 'w': wb, 'f': fb, 'sex': gb})
ok = np.isfinite(xb)
r = call('fitybyx.fit_poly', table=tid, y='weight', x='height', degree=1, want_rows=True)
lr = stats.linregress(xb[ok], yb[ok])
est = {e['term']: e for e in r['estimates']['rows']}
check.near('Fit Line slope = linregress', est['height']['estimate'], lr.slope)
check.near('Fit Line intercept = linregress', est['Intercept']['estimate'], lr.intercept)
check.near('Fit Line slope SE = linregress', est['height']['se'], lr.stderr)
sof = {s['stat']: s['value'] for s in r['summary']['rows']}
check.near('RSquare = r²', sof['RSquare'], lr.rvalue ** 2)
check('Summary of Fit names', list(sof), ['RSquare', 'RSquare Adj', 'Root Mean Square Error', 'Mean of Response', 'Observations (or Sum Wgts)'])
check('ANOVA sources', [a['source'] for a in r['anova']['rows']], ['Model', 'Error', 'C. Total'])
check.near('ANOVA F = t²', r['anova']['rows'][0]['f'], (lr.slope / lr.stderr) ** 2)
ref = sm.OLS(yb[ok], sm.add_constant(xb[ok])).fit()
check('rows are the table rows (row 3 missing)', r['row_values']['rows'][:5], [0, 1, 2, 4, 5])
check.near('saved residual', r['row_values']['residual'][4], float(ref.resid[4]))
check.near('studentized residual', r['row_values']['studentized'][2], float(ref.get_influence().resid_studentized_internal[2]))
pf = ref.get_prediction(np.array([[1.0, float(np.nanmin(xb))]])).summary_frame(alpha=0.05)
check.near('confidence curve of the fit at the left end', r['curve']['lo_fit'][0], float(pf['mean_ci_lower'].iloc[0]))
check.near('confidence curve of an individual', r['curve']['hi_ind'][0], float(pf['obs_ci_upper'].iloc[0]))
# lack of fit: the heights are rounded, so they repeat
lof = r['lack_of_fit']
ux, inv = np.unique(xb[ok], return_inverse=True)
pe = float(sum(np.sum((yb[ok][inv == i] - yb[ok][inv == i].mean()) ** 2) for i in range(len(ux))))
check('lack of fit shown', lof is not None, True)
check.near('pure error SS', lof['rows'][1]['ss'], pe)
check('pure error DF', lof['rows'][1]['df'], float(ok.sum() - len(ux)))
check.near('Max RSq', lof['max_rsq'], 1 - pe / float(ref.centered_tss))
# weights: WLS
rw = call('fitybyx.fit_poly', table=tid, y='weight', x='height', degree=1, weight='w')
refw = sm.WLS(yb[ok], sm.add_constant(xb[ok]), weights=wb[ok]).fit()
check.near('weighted slope = WLS', {e['term']: e for e in rw['estimates']['rows']}['height']['estimate'], float(refw.params[1]))
check.near('weighted slope SE = WLS', {e['term']: e for e in rw['estimates']['rows']}['height']['se'], float(refw.bse[1]))
# Freq: the same as repeating the rows
rf = call('fitybyx.fit_poly', table=tid, y='weight', x='height', degree=2, freq='f')
reps = fb[ok].astype(int)
xe, ye = np.repeat(xb[ok], reps), np.repeat(yb[ok], reps)
m = xb[ok].mean()   # models.build centres at the mean of the rows
refe = sm.OLS(ye, np.column_stack([np.ones(len(xe)), xe, (xe - m) ** 2])).fit()
estf = [e for e in rf['estimates']['rows']]
check.near('Freq: estimates as if the rows were repeated', estf[2]['estimate'], float(refe.params[2]))
check.near('Freq: standard errors counted from Freq', estf[1]['se'], float(refe.bse[1]))
check.near('Freq: RSquare Adj', {s['stat']: s['value'] for s in rf['summary']['rows']}['RSquare Adj'], float(refe.rsquared_adj))
check('Freq: observations', {s['stat']: s['value'] for s in rf['summary']['rows']}['Observations (or Sum Wgts)'], float(reps.sum()))
check('code for the line', 'smf.ols' in r['code'], True)
check('code with Freq sets df_resid', 'df_resid' in rf['code'], True)
# a group's rows (Group By) and the where filter in the code
rg = call('fitybyx.fit_poly', table=tid, y='weight', x='height', degree=1, rows=[i for i in range(n) if gb[i] == 'F'], where=[{'column': 'sex', 'value': 'F'}])
sel = ok & (np.array(gb) == 'F')
check.near('a group\'s fit', {e['term']: e for e in rg['estimates']['rows']}['height']['estimate'], stats.linregress(xb[sel], yb[sel]).slope)
check('the group in the code', 'df[df["sex"] == "F"]' in rg['code'], True)

# Fit Mean
r = call('fitybyx.fit_mean', table=tid, y='weight', x='height')
check.near('Fit Mean', r['mean'], float(yb[ok].mean()))
check.near('Fit Mean Std Dev [RMSE]', r['sd'], float(yb[ok].std(ddof=1)))
check.near('Fit Mean Std Error', r['se'], float(yb[ok].std(ddof=1) / math.sqrt(ok.sum())))

# Summary Statistics
r = call('fitybyx.bivariate', table=tid, y='weight', x='height')
check.near('summary: correlation', r['r'], float(np.corrcoef(xb[ok], yb[ok])[0, 1]))
check.near('summary: sd of X', r['sd_x'], float(np.std(xb[ok], ddof=1)))

# Fit Special: log-log against OLS on the logs, on the original scale
xs = rng.uniform(1, 20, 60)
ys = 3 * xs ** 0.6 * np.exp(rng.normal(0, 0.1, 60))
tid2 = table({'x': xs, 'y': ys})
r = call('fitybyx.fit_special', table=tid2, y='y', x='x', ytr='log', xtr='log', want_rows=True)
refl = sm.OLS(np.log(ys), sm.add_constant(np.log(xs))).fit()
check('Fit Special title', r['title'], 'Transformed Fit Log to Log')
check.near('log-log slope', r['terms'][1]['estimate'], float(refl.params[1]))
check('log-log term name', r['terms'][1]['term'], 'Log(x)')
pred = np.exp(refl.fittedvalues)
check.near('fit measured on the original scale: SSE', r['original']['rows'][0]['value'], float(np.sum((ys - pred) ** 2)))
check.near('curve back-transformed', r['curve']['fit'][0], float(np.exp(refl.params[0] + refl.params[1] * np.log(xs.min()))))
r = call('fitybyx.fit_special', table=tid2, y='y', x='x', ytr='none', xtr='sqrt', slope=1.5)
check.near('slope held: the intercept is the mean of y - b x', r['terms'][0]['estimate'], float(np.mean(ys - 1.5 * np.sqrt(xs))))
r = call('fitybyx.fit_special', table=tid2, y='y', x='x', ytr='reciprocal', xtr='none')
lo, hi = np.array(r['curve']['lo_fit']), np.array(r['curve']['hi_fit'])
check('reciprocal: the confidence curves stay ordered', bool(np.all(lo <= np.array(r['curve']['fit']) + 1e-12) and np.all(np.array(r['curve']['fit']) <= hi + 1e-12)), True)

# Fit Spline: scipy on rows combined by X
r = call('fitybyx.fit_spline', table=tid, y='weight', x='height', lam=1000, want_rows=True)
ux, inv = np.unique(xb[ok], return_inverse=True)
Wc = np.bincount(inv)
yc = np.bincount(inv, weights=yb[ok]) / Wc
spl = make_smoothing_spline(ux, yc, w=Wc.astype(float), lam=1000.0)
check.near('spline prediction = make_smoothing_spline', r['row_values']['predicted'][10], float(spl(xb[ok][10])))
sse = float(np.sum((yb[ok] - spl(xb[ok])) ** 2))
check.near('spline SSE', r['sse'], sse)
r2 = call('fitybyx.fit_spline', table=tid, y='weight', x='height', lam=1e12)
check.near('a stiff spline is the line', r2['rsquare'], lr.rvalue ** 2, rel=1e-4)

# Kernel smoother = statsmodels lowess
from statsmodels.nonparametric.smoothers_lowess import lowess
r = call('fitybyx.fit_lowess', table=tid, y='weight', x='height', frac=0.5, it=2, want_rows=True)
lw = lowess(yb[ok], xb[ok], frac=0.5, it=2, return_sorted=False)
check.near('lowess fitted value', r['row_values']['predicted'][7], float(lw[7]))

# Fit Each Value
r = call('fitybyx.fit_each', table=tid, y='weight', x='height')
check.near('Fit Each Value SS is the pure error', r['sse'], pe)
check('Fit Each Value unique values', r['n_unique'], len(ux))

# Robust and quantile fits
xr = rng.uniform(0, 10, 80)
yr = 1 + 2 * xr + rng.standard_t(2, 80)
yr[:4] += 40
tid3 = table({'x': xr, 'y': yr})
for method, norm in (('huber', sm.robust.norms.HuberT()), ('bisquare', sm.robust.norms.TukeyBiweight())):
    r = call('fitybyx.fit_robust', table=tid3, y='y', x='x', method=method)
    ref = sm.RLM(yr, sm.add_constant(xr), M=norm).fit()
    check.near(f'robust ({method}) slope = RLM', r['terms'][1]['estimate'], float(ref.params[1]))
    check.near(f'robust ({method}) slope SE = RLM', r['estimates']['rows'][1]['se'], float(ref.bse[1]))
engel = sm.datasets.engel.load_pandas().data
tid4 = table({'income': engel['income'].tolist(), 'foodexp': engel['foodexp'].tolist()})
r = call('fitybyx.fit_quantile', table=tid4, y='foodexp', x='income', tau=0.5)
check.near('Engel median regression intercept (quantreg: 81.48225)', r['terms'][0]['estimate'], 81.48225, rel=1e-5)
check.near('Engel median regression slope (quantreg: 0.5601806)', r['terms'][1]['estimate'], 0.5601806, rel=1e-5)
ref = smf.quantreg('foodexp ~ income', engel).fit(q=0.5)
check.near('Engel slope SE = QuantReg', r['estimates']['rows'][1]['se'], float(ref.bse.iloc[1]))
r = call('fitybyx.fit_quantile', table=tid4, y='foodexp', x='income', tau=0.9)
check.near('Engel 0.9 quantile slope = QuantReg', r['terms'][1]['estimate'], float(smf.quantreg('foodexp ~ income', engel).fit(q=0.9).params.iloc[1]))

# Orthogonal fits: the eigenvector, the geometric mean slope, X on Y, the jackknife
xo, yo = xb[ok], yb[ok]
S = np.cov(xo, yo)
r = call('fitybyx.fit_orthogonal', table=tid, y='weight', x='height', mode='equal')
ev = np.linalg.eigh(S)[1][:, -1]
check.near('equal variances: the major axis', r['slope'], float(ev[1] / ev[0]))
r = call('fitybyx.fit_orthogonal', table=tid, y='weight', x='height', mode='univariate')
check.near('univariate variances: slope sy/sx', r['slope'], float(np.sign(S[0, 1]) * math.sqrt(S[1, 1] / S[0, 0])))
check.near('univariate variances: the ratio', r['ratio'], float(S[1, 1] / S[0, 0]))
jk = []
for i in range(len(xo)):
    Si = np.cov(np.delete(xo, i), np.delete(yo, i))
    jk.append(np.sign(Si[0, 1]) * math.sqrt(Si[1, 1] / Si[0, 0]))
jk = np.array(jk)
check.near('jackknife standard error of the slope', r['se_slope'], float(math.sqrt((len(jk) - 1) / len(jk) * np.sum((jk - jk.mean()) ** 2))))
r = call('fitybyx.fit_orthogonal', table=tid, y='weight', x='height', mode='x_to_y')
check.near('Fit X to Y: slope syy/sxy', r['slope'], float(S[1, 1] / S[0, 1]))
r = call('fitybyx.fit_orthogonal', table=tid, y='weight', x='height', mode='ratio', ratio=4.0)
d4 = 4.0
b4 = (S[1, 1] - d4 * S[0, 0] + math.sqrt((S[1, 1] - d4 * S[0, 0]) ** 2 + 4 * d4 * S[0, 1] ** 2)) / (2 * S[0, 1])
check.near('a given variance ratio (Deming)', r['slope'], b4)

# Density ellipse and the correlation
r = call('fitybyx.density_ellipse', table=tid, y='weight', x='height', levels=[0.9, 0.5])
pr = stats.pearsonr(xo, yo)
check.near('correlation = pearsonr', r['r'], float(pr.statistic))
check.near('Signif. Prob = pearsonr', r['p'], float(pr.pvalue))
check.near('Fisher z interval', r['lower'], float(pr.confidence_interval(0.95).low))
e = r['ellipses'][0]
pt = np.array([e['x'][17], e['y'][17]]) - np.array([xo.mean(), yo.mean()])
check.near('the ellipse holds P = 0.9', float(pt @ np.linalg.solve(S, pt)), float(stats.chi2.ppf(0.9, 2)))
r = call('fitybyx.nonpar_density', table=tid, y='weight', x='height')
check('nonpar density: a grid and five contours', (len(r['z']), len(r['z'][0]), len(r['levels'])), (64, 64, 5))
check('contour levels rise with q', [l['value'] for l in r['levels']] == sorted(l['value'] for l in r['levels']), True)

# ---- Oneway ---------------------------------------------------------------------------------
k = 4
nlev = [9, 12, 10, 11]
lv = ['A', 'B', 'C', 'D']
g = np.repeat(lv, nlev)
yo = np.concatenate([rng.normal(mu, sd, m) for mu, sd, m in zip([10, 11.5, 12, 10.4], [1.0, 1.3, 0.8, 1.6], nlev)])
blk = np.tile(['b1', 'b2', 'b3'], 20)[:len(g)]
fo = rng.integers(1, 3, len(g)).astype(float)
tid = table({'y': yo, 'g': g.tolist(), 'blk': blk.tolist(), 'f': fo})
dfo = pd.DataFrame({'y': yo, 'g': g, 'blk': blk})
groups = [yo[g == l] for l in lv]
r = call('fitybyx.oneway', table=tid, y='y', x='g')
fo_ = stats.f_oneway(*groups)
check.near('ANOVA F = f_oneway', r['anova']['rows'][0]['f'], float(fo_.statistic))
check.near('ANOVA p = f_oneway', r['anova']['rows'][0]['p'], float(fo_.pvalue))
check('ANOVA source is X', r['anova']['rows'][0]['source'], 'g')
check('Oneway Summary of Fit names', [s['stat'] for s in r['summary']['rows']][:2], ['Rsquare', 'Adj Rsquare'])
mse = float(sum(np.sum((s - s.mean()) ** 2) for s in groups) / (len(yo) - k))
check.near('Means for Oneway Anova: pooled Std Error', r['levels'][1]['se_pooled'], math.sqrt(mse / nlev[1]))
check.near('Means and Std Deviations: std dev', r['levels'][2]['sd'], float(groups[2].std(ddof=1)))
check.near('quantiles (n+1)p', r['levels'][0]['q25'], float(np.quantile(groups[0], 0.25, method='weibull')))
a3 = sm.stats.anova_lm(smf.ols('y ~ C(g, Sum) + C(blk, Sum)', dfo).fit(), typ=3)
rb = call('fitybyx.oneway', table=tid, y='y', x='g', block='blk')
check.near('randomized block: X', rb['anova']['rows'][0]['ss'], float(a3.loc['C(g, Sum)', 'sum_sq']))
check.near('randomized block: Block', rb['anova']['rows'][1]['p'], float(a3.loc['C(blk, Sum)', 'PR(>F)']))
check('randomized block sources', [a['source'] for a in rb['anova']['rows']], ['g', 'blk', 'Error', 'C. Total'])
refb = smf.ols('y ~ C(g, Sum) + C(blk, Sum)', dfo).fit()
lsm = np.mean([refb.predict(pd.DataFrame({'g': ['B'], 'blk': [b]}))[0] for b in ['b1', 'b2', 'b3']])
check.near('randomized block: least squares mean', rb['levels'][1]['lsmean'], float(lsm))
rf = call('fitybyx.oneway', table=tid, y='y', x='g', freq='f')
ye, ge = np.repeat(yo, fo.astype(int)), np.repeat(g, fo.astype(int))
check.near('Freq in the ANOVA', rf['anova']['rows'][0]['f'], float(stats.f_oneway(*[ye[ge == l] for l in lv]).statistic))
# two levels: pooled t and Welch
t2 = table({'y': np.concatenate([groups[0], groups[1]]), 'g': ['A'] * nlev[0] + ['B'] * nlev[1]})
r = call('fitybyx.oneway', table=t2, y='y', x='g')
tt = stats.ttest_ind(groups[1], groups[0])
check.near('pooled t (second level minus first)', r['pooled_t']['t'], float(tt.statistic))
r = call('fitybyx.oneway_ttest', table=t2, y='y', x='g')
tw = stats.ttest_ind(groups[1], groups[0], equal_var=False)
check.near('t Test (unequal variances)', r['t'], float(tw.statistic))
check.near('t Test df', r['df'], float(tw.df))
check.near('t Test p', r['p'], float(tw.pvalue))

# comparisons
r = call('fitybyx.oneway_compare', table=tid, y='y', x='g', method='student')
check.near('Student\'s t quantile', r['quantile']['value'], float(stats.t.ppf(0.975, len(yo) - k)))
p0 = [p for p in r['pairs'] if {p['i'], p['j']} == {0, 2}][0]
se02 = math.sqrt(mse * (1 / nlev[0] + 1 / nlev[2]))
check.near('Student\'s t: Std Err Dif', p0['se'], se02)
check.near('Student\'s t: p-Value', p0['p'], float(2 * stats.t.sf(abs(groups[0].mean() - groups[2].mean()) / se02, len(yo) - k)))
check('connecting letters for every level', sorted(l['index'] for l in r['letters']), [0, 1, 2, 3])
r = call('fitybyx.oneway_compare', table=tid, y='y', x='g', method='tukey')
from statsmodels.stats.multicomp import pairwise_tukeyhsd
tk = pairwise_tukeyhsd(yo, g)
check.near('Tukey q* = studentized range / √2', r['quantile']['value'], float(stats.studentized_range.ppf(0.95, k, len(yo) - k) / math.sqrt(2)))
p13 = [p for p in r['pairs'] if {p['i'], p['j']} == {1, 3}][0]
m13 = [i for i, (a, b) in enumerate([(a, b) for a in range(k) for b in range(a + 1, k)]) if (a, b) == (1, 3)][0]
check.near('Tukey difference = pairwise_tukeyhsd', p13['diff'], abs(float(tk.meandiffs[m13])))
check.near('Tukey Std Err Dif = √2 std_pairs', p13['se'], float(tk.std_pairs[m13] * math.sqrt(2)))
check.near('Tukey p = studentized range', p13['p'], float(stats.studentized_range.sf(abs(tk.meandiffs[m13]) / tk.std_pairs[m13], k, len(yo) - k)))
check.near('Tukey interval = pairwise_tukeyhsd (psturng q, 3 digits)', p13['upper'], float(np.max(np.abs(tk.confint[m13]))), rel=2e-3)
r = call('fitybyx.oneway_compare', table=tid, y='y', x='g', method='dunnett', control='A')
dn = stats.dunnett(groups[1], groups[2], groups[3], control=groups[0], rng=np.random.default_rng(20260926))
pc = {p['i']: p for p in r['pairs']}
check.near('Dunnett p = scipy', pc[2]['p'], float(dn.pvalue[1]), rel=1e-6)
check.near('Dunnett interval = scipy', pc[3]['lower'], float(dn.confidence_interval(0.95).low[2]), rel=1e-6)
check('Dunnett |d| between t and Bonferroni', stats.t.ppf(0.975, len(yo) - k) < r['quantile']['value'] < stats.t.ppf(1 - 0.05 / 6, len(yo) - k), True)
# the letters algorithm on a textbook pattern: A=B, B=C, A≠C
from smui.fit_y_by_x import _letters
lets, ncol = _letters([0, 1, 2], [[False, False, True], [False, False, False], [True, False, False]])
check('connecting letters A, A B, B', [lets[0], lets[1], lets[2]], ['A', 'A B', '  B'])

# nonparametric tests
r = call('fitybyx.oneway_nonpar', table=tid, y='y', x='g', test='wilcoxon')
check.near('Kruskal-Wallis = scipy kruskal', r['chisq'], float(stats.kruskal(*groups).statistic))
r2 = call('fitybyx.oneway_nonpar', table=t2, y='y', x='g', test='wilcoxon')
check.near('2-sample Wilcoxon p = mannwhitneyu (continuity)', r2['two_sample']['p'], float(stats.mannwhitneyu(groups[0], groups[1], method='asymptotic').pvalue))
r = call('fitybyx.oneway_nonpar', table=tid, y='y', x='g', test='median')
mt = stats.median_test(*groups, correction=False)
check.near('median test = scipy × (N−1)/N', r['chisq'], float(mt.statistic) * (len(yo) - 1) / len(yo))
r = call('fitybyx.oneway_nonpar', table=tid, y='y', x='g', test='vdw')
a = stats.norm.ppf(stats.rankdata(yo) / (len(yo) + 1))
vw = (len(yo) - 1) * sum(len(a[g == l]) * (a[g == l].mean() - a.mean()) ** 2 for l in lv) / np.sum((a - a.mean()) ** 2)
check.near('van der Waerden chi-square', r['chisq'], float(vw))
r = call('fitybyx.oneway_ks', table=t2, y='y', x='g')
ks = stats.ks_2samp(groups[0], groups[1])
check.near('Kolmogorov-Smirnov D', r['D'], float(ks.statistic))
check.near('Kolmogorov-Smirnov p', r['p'], float(ks.pvalue))
check.near('KSa = D √(n1 n2/n)', r['KSa'], float(ks.statistic) * math.sqrt(nlev[0] * nlev[1] / (nlev[0] + nlev[1])))

# nonparametric comparisons
r = call('fitybyx.oneway_nonpar_mc', table=tid, y='y', x='g', method='wilcoxon')
p = [q for q in r['pairs'] if (q['i'], q['j']) == (0, 1)][0]
check.near('Wilcoxon each pair p = mannwhitneyu', p['p'], float(stats.mannwhitneyu(groups[0], groups[1], method='asymptotic').pvalue))
check.near('Hodges-Lehmann = median of the differences', p['hl'], float(np.median(np.subtract.outer(groups[0], groups[1]))))
r = call('fitybyx.oneway_nonpar_mc', table=tid, y='y', x='g', method='steel_dwass')
p = [q for q in r['pairs'] if (q['i'], q['j']) == (1, 3)][0]
ab = np.concatenate([groups[1], groups[3]])
rk = stats.rankdata(ab)
S_ = rk[:nlev[1]].sum()
z_ = (S_ - nlev[1] * (len(ab) + 1) / 2) / math.sqrt(nlev[1] * nlev[3] * np.var(rk, ddof=1) / len(ab))
check.near('Steel-Dwass Z', p['z'], float(z_))
check.near('Steel-Dwass p = studentized range (df ∞)', p['p'], float(stats.studentized_range.sf(abs(z_) * math.sqrt(2), k, np.inf)))
r = call('fitybyx.oneway_nonpar_mc', table=tid, y='y', x='g', method='dunn_all')
rk = stats.rankdata(yo)
N = len(yo)
s2 = N * (N + 1) / 12
rb_ = [rk[g == l].mean() for l in lv]
z02 = (rb_[0] - rb_[2]) / math.sqrt(s2 * (1 / nlev[0] + 1 / nlev[2]))
p = [q for q in r['pairs'] if (q['i'], q['j']) == (0, 2)][0]
check.near('Dunn Z (joint ranks)', p['z'], float(z02))
check.near('Dunn p (Bonferroni over 6 pairs)', p['p'], float(min(1, 6 * 2 * stats.norm.sf(abs(z02)))))
r = call('fitybyx.oneway_nonpar_mc', table=tid, y='y', x='g', method='steel_control', control='A')
check('Steel with control: three comparisons', len(r['pairs']), 3)
check('Steel with control p-values are probabilities', all(0 <= q['p'] <= 1 for q in r['pairs']), True)

# variances
r = call('fitybyx.oneway_unequal_var', table=tid, y='y', x='g')
tv = {t['test']: t for t in r['tests']}
check.near('Levene = scipy levene(mean)', tv['Levene']['f'], float(stats.levene(*groups, center='mean').statistic))
check.near('Brown-Forsythe = scipy levene(median)', tv['Brown-Forsythe']['p'], float(stats.levene(*groups, center='median').pvalue))
check.near('Bartlett p = scipy', tv['Bartlett']['p'], float(stats.bartlett(*groups).pvalue))
check.near('O\'Brien[.5] = f_oneway of obrientransform', tv['O\'Brien[.5]']['f'], float(stats.f_oneway(*stats.obrientransform(*groups)).statistic))
from statsmodels.stats.oneway import anova_oneway
wr = anova_oneway(yo, g, use_var='unequal')
check.near('Welch ANOVA F', r['welch']['f'], float(wr.statistic))
check.near('Welch ANOVA df', r['welch']['dfd'], float(wr.df_denom))
r2 = call('fitybyx.oneway_unequal_var', table=t2, y='y', x='g')
check.near('Welch t² = F for two levels', r2['welch']['t'] ** 2, float(stats.ttest_ind(groups[0], groups[1], equal_var=False).statistic ** 2))

# equivalence, power, ANOM, densities
from statsmodels.stats.weightstats import ttost_ind
r = call('fitybyx.oneway_equivalence', table=t2, y='y', x='g', delta=2.0)
check.near('TOST p = ttost_ind', r['pairs'][0]['p'], float(ttost_ind(groups[1], groups[0], -2.0, 2.0, usevar='pooled')[0]))
from statsmodels.stats.power import FTestAnovaPower
r = call('fitybyx.oneway_power', table=tid, y='y', x='g', sigma=1.2, delta=0.8, nobs=[42, 80])
check.near('power = FTestAnovaPower', r['rows'][1]['power'], float(FTestAnovaPower().power(effect_size=0.8 / 1.2, nobs=80, alpha=0.05, k_groups=k)))
lam = 80 * (0.8 / 1.2) ** 2
check.near('power = noncentral F', r['rows'][1]['power'], float(stats.ncf.sf(stats.f.ppf(0.95, k - 1, 80 - k), k - 1, 80 - k, lam)), rel=1e-6)
lsn = r['lsn']
check.near('LSN: F reaches its critical value', lsn * 0.8 ** 2 / ((k - 1) * 1.2 ** 2), float(stats.f.ppf(0.95, k - 1, lsn - k)), rel=1e-6)
r = call('fitybyx.oneway_anom', table=tid, y='y', x='g')
h = r['h']
# the ANOM critical value by simulation of the multivariate t
sim = np.random.default_rng(7)
M = 200000
nn = np.array(nlev, float)
Z = sim.normal(size=(M, k)) / np.sqrt(nn)
gm = (Z * nn).sum(1) / nn.sum()
T = (Z - gm[:, None]) / np.sqrt((nn.sum() - nn) / (nn.sum() * nn)) / np.sqrt(sim.chisquare(nn.sum() - k, M) / (nn.sum() - k))[:, None]
cover = float(np.mean(np.abs(T).max(1) <= h))
check.near('ANOM h covers 95% (simulation)', cover, 0.95, abs_=0.003)
check.near('ANOM upper decision limit', r['levels'][0]['udl'], float(yo.mean() + h * math.sqrt(mse) * math.sqrt((nn.sum() - nn[0]) / (nn.sum() * nn[0]))))
r = call('fitybyx.oneway_densities', table=tid, y='y', x='g')
kd = stats.gaussian_kde(groups[1])
check.near('densities = gaussian_kde', r['levels'][1]['density'][40], float(kd(r['x'][40])[0]))

# ---- Logistic ------------------------------------------------------------------------------
n = 240
dose = rng.choice([0, 10, 20, 40, 80], n).astype(float)
eta = -1.4 + 0.035 * dose
resp = np.where(rng.uniform(size=n) < 1 / (1 + np.exp(-eta)), 'yes', 'no')
wl = rng.integers(1, 4, n).astype(float)
tid = table({'dose': dose, 'response': resp.tolist(), 'f': wl}, levels={'response': ['no', 'yes']})
r = call('fitybyx.logistic', table=tid, y='response', x='dose')
yb_ = (resp == 'no').astype(float)   # JMP: the log odds of the first level
ref = sm.Logit(yb_, sm.add_constant(dose)).fit(disp=0)
est = {e['term']: e for e in r['estimates']}
check.near('binary: slope = Logit on the first level', est['dose']['estimate'], float(ref.params[1]))
check.near('binary: slope SE', est['dose']['se'], float(ref.bse[1]))
check.near('binary: Wald ChiSquare', est['dose']['chisq'], float((ref.params[1] / ref.bse[1]) ** 2))
check.near('Whole Model: ChiSquare = LR', r['whole'][0]['chisq'], float(ref.llr))
check.near('Whole Model: p', r['whole'][0]['p'], float(ref.llr_pvalue))
check.near('RSquare (U) = McFadden', r['rsquare_u'], float(ref.prsquared))
check.near('-LogLikelihood Full', r['whole'][1]['nll'], float(-ref.llf))
check.near('unit odds ratio', r['odds'][0]['unit'], float(np.exp(ref.params[1])))
p_yes = 1 - ref.predict(sm.add_constant(dose))
pos = resp == 'yes'
auc_ref = stats.mannwhitneyu(p_yes[pos], p_yes[~pos]).statistic / (pos.sum() * (~pos).sum())
roc = r['roc'][0]
pno = ref.predict(sm.add_constant(dose))
auc_no = stats.mannwhitneyu(pno[~pos], pno[pos]).statistic / (pos.sum() * (~pos).sum())
check.near('ROC AUC = Mann-Whitney U / (n1 n0)', roc['auc'], float(auc_no))
check('the curve has a cumulative probability per boundary', len(r['curve']['cum']), 1)
r2 = call('fitybyx.logistic', table=tid, y='response', x='dose', target='yes')
check.near('target level yes: the slope changes sign', {e['term']: e for e in r2['estimates']}['dose']['estimate'], -float(ref.params[1]))
ri = call('fitybyx.logistic_inverse', table=tid, y='response', x='dose', probs=[0.5, 0.25])
xp = ri['rows'][0]['x']
check.near('inverse prediction: P(first level) = 0.5 there', float(ref.predict(np.array([[1.0, xp]]))[0]), 0.5)
check('Fieller limits bracket the estimate', ri['rows'][1]['lower'] < ri['rows'][1]['x'] < ri['rows'][1]['upper'], True)
rs = call('fitybyx.logistic_rows', table=tid, y='response', x='dose')
check.near('saved probability', rs['probs'][0][5], float(pno[5]))
# Freq: GLM with frequency weights is the Logit of the repeated rows
rf = call('fitybyx.logistic', table=tid, y='response', x='dose', freq='f')
refe = sm.Logit(np.repeat(yb_, wl.astype(int)), sm.add_constant(np.repeat(dose, wl.astype(int)))).fit(disp=0)
check.near('Freq: the slope of the repeated rows', {e['term']: e for e in rf['estimates']}['dose']['estimate'], float(refe.params[1]))
check.near('Freq: its SE', {e['term']: e for e in rf['estimates']}['dose']['se'], float(refe.bse[1]))
check.near('Freq: the LR chi-square', rf['whole'][0]['chisq'], float(refe.llr), rel=1e-7)
# nominal: MNLogit, the last level the reference
cat3 = np.where(dose > 30, rng.choice(['a', 'b', 'c'], n, p=[0.2, 0.3, 0.5]), rng.choice(['a', 'b', 'c'], n, p=[0.5, 0.3, 0.2]))
tid5 = table({'dose': dose, 'k': cat3.tolist()})
r = call('fitybyx.logistic', table=tid5, y='k', x='dose')
codes = pd.Categorical(cat3, categories=['c', 'a', 'b']).codes
refm = sm.MNLogit(codes, sm.add_constant(dose)).fit(disp=0)
ea = [e for e in r['estimates'] if e['group'] == 0 and e['term'] == 'dose'][0]
check.near('nominal: log odds a/c slope = MNLogit', ea['estimate'], float(np.asarray(refm.params)[1, 0]))
check.near('nominal: its SE', ea['se'], float(np.asarray(refm.bse)[1, 0]))
check.near('nominal: LR chi-square', r['whole'][0]['chisq'], float(refm.llr))
check('nominal: the Whole Model DF', r['whole'][0]['df'], 2)
# ordinal: OrderedModel, cumulative logits
from statsmodels.miscmodels.ordinal_model import OrderedModel
lat = 0.04 * dose + rng.logistic(size=n)
ordv = np.digitize(lat, [0.5, 1.5, 2.8])
names = np.array(['none', 'mild', 'moderate', 'severe'])[ordv]
tid6 = table({'dose': dose, 'sev': names.tolist()}, types={'sev': 'ordinal'}, levels={'sev': ['none', 'mild', 'moderate', 'severe']})
r = call('fitybyx.logistic', table=tid6, y='sev', x='dose')
om = OrderedModel(pd.Series(pd.Categorical(names, categories=['none', 'mild', 'moderate', 'severe'], ordered=True)), dose[:, None], distr='logit')
ro = om.fit(method='bfgs', disp=0, maxiter=500)
th = om.transform_threshold_params(ro.params)[1:-1]
est = {e['term']: e for e in r['estimates']}
check.near('ordinal: slope = −(OrderedModel\'s)', est['dose']['estimate'], -float(ro.params.iloc[0]), rel=1e-5)
check.near('ordinal: the first intercept = the first threshold', est['Intercept[none]']['estimate'], float(th[0]), rel=1e-5)
check.near('ordinal: its SE = OrderedModel\'s', est['Intercept[none]']['se'], float(ro.bse.iloc[1]), rel=1e-4)
check.near('ordinal: the third intercept', est['Intercept[moderate]']['estimate'], float(th[2]), rel=1e-5)
# the SE of a later threshold by the delta method, the gradient by finite differences
p_ = np.asarray(ro.params, float)
cv = np.asarray(ro.cov_params(), float)
gr = np.zeros(len(p_))
for j in range(len(p_)):
    e_ = np.zeros(len(p_))
    e_[j] = 1e-6
    gr[j] = (om.transform_threshold_params(p_ + e_)[3] - om.transform_threshold_params(p_ - e_)[3]) / 2e-6
check.near('ordinal: a later intercept\'s SE (delta method)', est['Intercept[moderate]']['se'], float(math.sqrt(gr @ cv @ gr)), rel=1e-4)
check.near('ordinal: LR chi-square', r['whole'][0]['chisq'], float(2 * (ro.llf - ro.llnull)), rel=1e-6)

# ---- Contingency ---------------------------------------------------------------------------
n = 300
tx = rng.choice(['placebo', 'low', 'high'], n)
ty = np.where(tx == 'high', rng.choice(['none', 'some', 'good'], n, p=[0.2, 0.3, 0.5]), rng.choice(['none', 'some', 'good'], n, p=[0.4, 0.35, 0.25]))
tid = table({'trt': tx.tolist(), 'out': ty.tolist()}, types={'trt': 'ordinal', 'out': 'ordinal'},
            levels={'trt': ['placebo', 'low', 'high'], 'out': ['none', 'some', 'good']})
r = call('fitybyx.contingency', table=tid, y='out', x='trt')
ct = pd.crosstab(pd.Categorical(tx, ['placebo', 'low', 'high']), pd.Categorical(ty, ['none', 'some', 'good'])).to_numpy()
check('counts: X levels as rows', np.array(r['counts']).astype(int).tolist(), ct.tolist())
pe = stats.chi2_contingency(ct, correction=False)
g2 = stats.chi2_contingency(ct, correction=False, lambda_='log-likelihood')
check.near('Pearson chi-square', r['tests'][1]['chisq'], float(pe.statistic))
check.near('likelihood ratio chi-square', r['tests'][0]['chisq'], float(g2.statistic))
check.near('-LogLike is G²/2', r['loglike']['nll'], float(g2.statistic) / 2)
Hy = -np.sum(ct.sum(0) * np.log(ct.sum(0) / n))
check.near('RSquare (U)', r['rsquare_u'], float(g2.statistic / 2 / Hy))
# measures of association
r = call('fitybyx.contingency_measures', table=tid, y='out', x='trt')
ms = {m['measure']: m for m in r['measures']}
xi = pd.Categorical(tx, ['placebo', 'low', 'high']).codes
yi = pd.Categorical(ty, ['none', 'some', 'good']).codes
check.near('Kendall\'s tau-b = scipy', ms['Kendall\'s Tau-b']['value'], float(stats.kendalltau(xi, yi).statistic))
check.near('Stuart\'s tau-c = scipy', ms['Stuart\'s Tau-c']['value'], float(stats.kendalltau(xi, yi, variant='c').statistic))
check.near('Somers\' D C|R = scipy somersd(x, y)', ms['Somers\' D C|R']['value'], float(stats.somersd(xi, yi).statistic))
check.near('Somers\' D R|C = scipy somersd(y, x)', ms['Somers\' D R|C']['value'], float(stats.somersd(yi, xi).statistic))
conc = disc = 0
for i in range(n):
    dx = np.sign(xi[i + 1:] - xi[i])
    dy = np.sign(yi[i + 1:] - yi[i])
    conc += int(np.sum(dx * dy > 0))
    disc += int(np.sum(dx * dy < 0))
check.near('gamma = (C − D)/(C + D), pairs counted', ms['Gamma']['value'], (conc - disc) / (conc + disc))
H = lambda p: -np.sum(p[p > 0] * np.log(p[p > 0]))
P = ct / n
U = (H(P.sum(1)) + H(P.sum(0)) - H(P.ravel())) / H(P.sum(0))
check.near('uncertainty coefficient C|R', ms['Uncertainty Coef C|R']['value'], float(U))
lamcr = (ct.max(1).sum() - ct.sum(0).max()) / (n - ct.sum(0).max())
check.near('lambda C|R', ms['Lambda Asymmetric C|R']['value'], float(lamcr))
check.near('Cramér\'s V = scipy', [o for o in r['other'] if o['measure'] == 'Cramér\'s V'][0]['value'], float(stats.contingency.association(ct, method='cramer')))
# the ASEs are delta-method standard errors: check each formula against the numeric delta method
from smui import fit_y_by_x as F


def measure_fn(name):
    def fn(p):
        return {m['measure']: m['value'] for m in F._measures(p * 1000.0)}[name]
    return fn


for name in ['Gamma', 'Kendall\'s Tau-b', 'Stuart\'s Tau-c', 'Somers\' D C|R', 'Somers\' D R|C', 'Uncertainty Coef C|R', 'Uncertainty Coef R|C', 'Uncertainty Coef Symmetric']:
    check.near(f'ASE of {name} = numeric delta method', ms[name]['se'], F._delta_se(measure_fn(name), ct.astype(float)), rel=1e-4)
# lambda is not differentiable where a row's largest count ties: a table without ties
tl = np.array([[40, 13, 22], [25, 38, 27], [16, 30, 45]], float)
ml = {m['measure']: m for m in F._measures(tl)}
for name in ['Lambda Asymmetric C|R', 'Lambda Asymmetric R|C', 'Lambda Symmetric']:
    fn = (lambda nm: (lambda p: {m['measure']: m['value'] for m in F._measures(p * 1000.0)}[nm]))(name)
    check.near(f'ASE of {name} = numeric delta method', ml[name]['se'], F._delta_se(fn, tl), rel=1e-4)
check.near('lambda C|R of the tie-free table', ml['Lambda Asymmetric C|R']['value'], (40 + 38 + 45 - 94) / (256 - 94))
# agreement
t2x = rng.choice(['a', 'b', 'c'], 150)
t2y = np.where(rng.uniform(size=150) < 0.6, t2x, rng.choice(['a', 'b', 'c'], 150))
tid7 = table({'r1': t2x.tolist(), 'r2': t2y.tolist()})
r = call('fitybyx.contingency_agreement', table=tid7, y='r2', x='r1')
from statsmodels.stats.inter_rater import cohens_kappa
from statsmodels.stats.contingency_tables import SquareTable, StratifiedTable, Table, Table2x2, mcnemar
sq = pd.crosstab(t2x, t2y).to_numpy()
kr = cohens_kappa(sq)
check.near('kappa = cohens_kappa', r['kappa'], float(kr.kappa))
check.near('kappa Std Err', r['se'], float(kr.std_kappa))
check.near('Bowker = SquareTable.symmetry', r['bowker']['chisq'], float(SquareTable(sq, shift_zeros=False).symmetry().statistic))
tid8 = table({'r1': ['a'] * 35 + ['b'] * 15, 'r2': ['a'] * 20 + ['b'] * 15 + ['a'] * 5 + ['b'] * 10})
check.near('kappa of [[20, 15], [5, 10]] is 0.2', call('fitybyx.contingency_agreement', table=tid8, y='r2', x='r1')['kappa'], 0.2)
# 2x2: relative risk, odds ratio, McNemar, Fisher
x2 = rng.choice(['drug', 'placebo'], 120)
y2 = np.where(x2 == 'drug', rng.choice(['yes', 'no'], 120, p=[0.6, 0.4]), rng.choice(['yes', 'no'], 120, p=[0.35, 0.65]))
tid9 = table({'t': x2.tolist(), 'r': y2.tolist()}, levels={'t': ['drug', 'placebo'], 'r': ['yes', 'no']})
t22 = pd.crosstab(pd.Categorical(x2, ['drug', 'placebo']), pd.Categorical(y2, ['yes', 'no'])).to_numpy()
r = call('fitybyx.contingency_2x2', table=tid9, y='r', x='t')
tt = Table2x2(t22, shift_zeros=False)
check.near('relative risk = Table2x2', r['risks'][0]['rr'], float(tt.riskratio))
check.near('relative risk lower limit', r['risks'][0]['lower'], float(tt.riskratio_confint()[0]))
check.near('odds ratio = Table2x2', r['odds']['or'], float(tt.oddsratio))
check.near('McNemar = statsmodels', r['mcnemar']['chisq'], float(mcnemar(t22, exact=False, correction=False).statistic))
rc = call('fitybyx.contingency', table=tid9, y='r', x='t')
check.near('Fisher 2-Tail = scipy', rc['fisher']['two'], float(stats.fisher_exact(t22).pvalue))
check.near('Fisher Left = scipy less', rc['fisher']['left'], float(stats.fisher_exact(t22, alternative='less').pvalue))
# CMH: the Chinese smoking tables (Agresti)
cs = sm.datasets.china_smoking.load_pandas().data
cities, xs_, ys_, fs_ = [], [], [], []
for city, row in cs.iterrows():
    for (xl, yl, v) in (('smoker', 'cancer', row['smoking_yes_cancer_yes']), ('smoker', 'healthy', row['smoking_yes_cancer_no']),
                        ('nonsmoker', 'cancer', row['smoking_no_cancer_yes']), ('nonsmoker', 'healthy', row['smoking_no_cancer_no'])):
        cities.append(city)
        xs_.append(xl)
        ys_.append(yl)
        fs_.append(float(v))
tid10 = table({'city': cities, 'smoking': xs_, 'lung': ys_, 'n': fs_}, levels={'smoking': ['smoker', 'nonsmoker'], 'lung': ['cancer', 'healthy']})
r = call('fitybyx.contingency_cmh', table=tid10, y='lung', x='smoking', strata='city', freq='n')
check.near('Mantel-Haenszel odds ratio (Agresti: 2.174)', r['or_mh'], 2.174, rel=5e-4)
check.near('CMH chi-square (280.14)', r['cmh']['chisq'], 280.14, rel=5e-5)
check.near('Breslow-Day (5.20)', r['breslow_day']['chisq'], 5.20, rel=2e-3)
check('eight strata', r['strata'], 8)
# Cochran-Armitage
tid11 = table({'d': np.repeat(['0', '10', '20', '40'], 50).tolist(), 'r': np.where(rng.uniform(size=200) < np.repeat([0.2, 0.3, 0.4, 0.55], 50), 'yes', 'no').tolist()},
              types={'d': 'ordinal'}, levels={'d': ['0', '10', '20', '40']})
r = call('fitybyx.contingency_trend', table=tid11, y='r', x='d')
ct4 = np.array(call('fitybyx.contingency', table=tid11, y='r', x='d')['counts'])
res = Table(ct4, shift_zeros=False).test_ordinal_association()
check.near('trend: statsmodels z', r['z_perm'], float(res.zscore))
sc = np.arange(4.0)
nj = ct4.sum(1)
p1 = ct4[:, 1].sum() / ct4.sum()
Tn = np.sum(ct4[:, 1] * (sc - np.sum(nj * sc) / nj.sum()))
zca = Tn / math.sqrt(p1 * (1 - p1) * np.sum(nj * (sc - np.sum(nj * sc) / nj.sum()) ** 2))
check.near('trend: the Cochran-Armitage Z (binomial variance)', r['z'], float(zca))
# Analysis of Means for Proportions: h covers 1 − α of the largest standardised deviation (simulated)
r = call('fitybyx.contingency_anomp', table=tid11, y='r', x='d')
ni = ct4.sum(1)
pb = ct4[:, 0].sum() / ct4.sum()
sim = np.random.default_rng(11)
Zs = sim.normal(size=(200000, 4)) / np.sqrt(ni)
gm = (Zs * ni).sum(1) / ni.sum()
Ts = (Zs - gm[:, None]) / np.sqrt((ni.sum() - ni) / (ni.sum() * ni))
check.near('ANOM for proportions: h covers 95% (simulation)', float(np.mean(np.abs(Ts).max(1) <= r['h'])), 0.95, abs_=0.003)
check.near('ANOM for proportions: a decision limit', r['levels'][2]['udl'], float(pb + r['h'] * math.sqrt(pb * (1 - pb) * (ni.sum() - ni[2]) / (ni.sum() * ni[2]))))
check('ANOM for proportions: the first level\'s proportions', [round(l['p'], 12) for l in r['levels']], [round(v, 12) for v in (ct4[:, 0] / ni).tolist()])
# correspondence analysis
r = call('fitybyx.contingency_ca', table=tid, y='out', x='trt')
check.near('correspondence analysis: N × inertia = Pearson chi-square', r['chisq'], float(pe.statistic))
check.near('portions add to one', sum(d['portion'] for d in r['details']), 1.0)

# ---- Matched Pairs ---------------------------------------------------------------------------
n = 40
before = rng.normal(120, 12, n)
after = before - 4 + rng.normal(0, 6, n)
grp = rng.choice(['x', 'y', 'z'], n).tolist()
after[5] = np.nan
tid = table({'before': before, 'after': after, 'grp': grp})
r = call('matchedpairs.analyze', table=tid, y1='before', y2='after', group='grp')
okm = np.isfinite(after)
tr = stats.ttest_rel(after[okm], before[okm])
check.near('paired t = ttest_rel', r['t'], float(tr.statistic))
check.near('paired p', r['p'], float(tr.pvalue))
check('pairs used', r['n'], int(okm.sum()))
dd = (after - before)[okm]
check.near('Wilcoxon signed rank p = scipy', r['wilcoxon']['p_two'], float(stats.wilcoxon(dd[dd != 0]).pvalue))
from statsmodels.stats.descriptivestats import sign_test
check.near('sign test = statsmodels', r['sign']['p_two'], float(sign_test(dd, 0)[1]))
check.near('correlation', r['r'], float(stats.pearsonr(before[okm], after[okm]).statistic))
ga = np.array(grp)[okm]
check.near('across groups: F of the differences', r['across_tests'][0]['f'], float(stats.f_oneway(*[dd[ga == v] for v in ['x', 'y', 'z']]).statistic))
check('the rows of the plot are table rows', r['rows'][:6], [0, 1, 2, 3, 4, 6])

# ---- Oneway ▸ Brunner-Munzel: the probability of superiority ------------------------------------
from statsmodels.stats.multitest import multipletests  # noqa: E402
from statsmodels.stats.nonparametric import rank_compare_2indep  # noqa: E402
# Munzel and Hauschke (2003): an ordinal score by treatment, given as counts (Freq). R's lawstat,
# brunner.munzel.test(new, active), as statsmodels' test suite records it
sc_lv = [-2, -1, 0, 1, 2]
new_n, act_n = [24, 37, 21, 19, 6], [11, 51, 22, 21, 7]
tmh = table({'score': sc_lv * 2, 'trt': ['new'] * 5 + ['active'] * 5, 'n': [float(v) for v in new_n + act_n]}, levels={'trt': ['new', 'active']})
r = call('fitybyx.oneway_brunner', table=tmh, y='score', x='trt', freq='n')
bm = r['pairs'][0]
check('Brunner-Munzel: the later level against the earlier (active vs new)', (bm['i'], bm['j'], bm['n1'], bm['n2']), (1, 0, 112, 107))
check.near('Brunner-Munzel statistic (lawstat 1.1757561456582)', bm['stat'], 1.1757561456582, rel=1e-11)
check.near('Brunner-Munzel df (lawstat 204.2984239868)', bm['df'], 204.2984239868, rel=1e-11)
check.near('Brunner-Munzel p (lawstat 0.2410606649547)', bm['p'], 0.2410606649547, rel=1e-10)
check.near('P(active > new) + ½P(=) (lawstat 0.5442256341789052)', bm['prob'], 0.5442256341789052, rel=1e-13)
check.near('its lower limit (lawstat 0.4700629827705593)', bm['lower'], 0.4700629827705593, rel=1e-11)
check.near('its upper limit (lawstat 0.6183882855872511)', bm['upper'], 0.6183882855872511, rel=1e-11)
xa, xn = np.repeat(sc_lv, act_n).astype(float), np.repeat(sc_lv, new_n).astype(float)
check.near('P is the Mann-Whitney U/(n1 n2)', bm['prob'], float(stats.mannwhitneyu(xa, xn).statistic / (len(xa) * len(xn))))
check.near('the statistic is scipy\'s brunnermunzel(new, active)', bm['stat'], float(stats.brunnermunzel(xn, xa).statistic), rel=1e-12)
check.near('the p-value is scipy\'s brunnermunzel', bm['p'], float(stats.brunnermunzel(xn, xa).pvalue), rel=1e-10)
check.near('Somers\' D = 2P − 1', bm['somersd'], 2 * bm['prob'] - 1)
refbm = rank_compare_2indep(xa, xn)
check.near('Prob>t = test_prob_superior(larger)', bm['p_greater'], float(refbm.test_prob_superior(alternative='larger').pvalue))
# the lawstat one-sided example of statsmodels' and scipy's tests: statistic 3.1374674823029505, p 0.0057862086661515377
xs1 = [1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 4, 1, 1]
ys1 = [3, 3, 4, 3, 1, 2, 3, 1, 1, 5, 4]
tbm = table({'v': xs1 + ys1, 'g': ['a'] * len(xs1) + ['b'] * len(ys1)})
r2 = call('fitybyx.oneway_brunner', table=tbm, y='v', x='g')
check.near('lawstat example: statistic 3.1374674823029505', r2['pairs'][0]['stat'], 3.1374674823029505, rel=1e-13)
check.near('lawstat example: p 0.0057862086661515377', r2['pairs'][0]['p'], 0.0057862086661515377, rel=1e-12)
check.near('lawstat example: one-sided p 0.0028931043330757342', r2['pairs'][0]['p_greater'], 0.0028931043330757342, rel=1e-12)
# several levels: every pair against statsmodels, Holm over the pairs
r4 = call('fitybyx.oneway_brunner', table=table({'y': yo, 'g': g.tolist()}), y='y', x='g')
p31 = [p_ for p_ in r4['pairs'] if (p_['i'], p_['j']) == (3, 1)][0]
ref31 = rank_compare_2indep(groups[3], groups[1])
check.near('a pair of four levels = rank_compare_2indep', p31['prob'], float(ref31.prob1))
check.near('its interval', p31['upper'], float(ref31.conf_int(alpha=0.05)[1]))
check('six pairs of four levels', len(r4['pairs']), 6)
check.near('Holm-adjusted p (statsmodels multipletests)', p31['p_holm'], float(multipletests([q['p'] for q in r4['pairs']], method='holm')[1][[(q['i'], q['j']) for q in r4['pairs']].index((3, 1))]))
# the equivalence test: two one-sided tests; at the (1 - 2 alpha) limits the p-value is alpha
lo90, hi90 = refbm.conf_int(alpha=0.1)
r5 = call('fitybyx.oneway_brunner', table=tmh, y='score', x='trt', freq='n', tost={'low': 0.4, 'upp': 0.6})
tt = refbm.tost_prob_superior(0.4, 0.6)
check.near('TOST p = tost_prob_superior', r5['tost']['pairs'][0]['p'], float(tt.pvalue))
check.near('TOST lower t = its larger test', r5['tost']['pairs'][0]['t_lower'], float(tt.results_larger.statistic))
check.near('the 90% interval shown', r5['tost']['pairs'][0]['upper'], float(hi90))
r6 = call('fitybyx.oneway_brunner', table=tmh, y='score', x='trt', freq='n', tost={'low': float(lo90), 'upp': float(hi90) * 1.05})
check.near('TOST at the lower 90% limit: p = 0.05', r6['tost']['pairs'][0]['p'], 0.05, rel=1e-9)
check('bounds outside [0, 1] are refused', 'error' in call('fitybyx.oneway_brunner', table=tmh, y='score', x='trt', tost={'low': 0.6, 'upp': 0.4}), True)
rsep = call('fitybyx.oneway_brunner', table=table({'v': [1.0, 2, 3, 7, 8, 9], 'g': ['a', 'a', 'a', 'b', 'b', 'b']}), y='v', x='g')
check('no overlap: P = 1, no test, a note', (rsep['pairs'][0]['prob'], rsep['pairs'][0]['p'], len(rsep['notes']) > 0, 'warnings' in rsep), (1.0, None, True, False))

# ---- Oneway ▸ Compare Rates: Poisson counts with an exposure ------------------------------------
from statsmodels.stats import rates as smr  # noqa: E402
# Gu, Ng, Tang and Schucany (2008), example 1: 60 events in 51477.5 person-years against 30 in
# 54308.7; each total split over three rows (units) here. Their one-sided p-values:
tgu = table({'events': [20.0, 25, 15, 10, 12, 8], 'arm': ['A'] * 3 + ['B'] * 3, 'py': [17000.0, 20000.0, 14477.5, 18000.0, 20000.0, 16308.7]})
gu = {'wald': 0.000356, 'score': 0.000316, 'score-log': 0.000200, 'wald-log': 0.000420, 'sqrt': 0.000285}
for meth, pv in gu.items():
    rr = call('fitybyx.oneway_rates', table=tgu, y='events', x='arm', exposure='py', method=meth, ci_method='score', control='B')
    check.near(f'Gu et al. example 1, {meth}: one-sided p {pv}', rr['pairs'][0]['p_greater'], pv, abs_=5e-6)
for meth, pv in (('exact-cond', 0.000428), ('cond-midp', 0.000310), ('etest-score', 0.000298), ('etest-wald', 0.000298)):
    rr = call('fitybyx.oneway_rates', table=tgu, y='events', x='arm', exposure='py', method=meth, ci_method='score', control='B')
    check.near(f'Gu et al. example 1, {meth}: one-sided p {pv}', rr['pairs'][0]['p_greater'], pv, abs_=5e-5)
rr = call('fitybyx.oneway_rates', table=tgu, y='events', x='arm', exposure='py', method='exact-cond', ci_method='exact-cond', control='B')
check.near('exact conditional two-sided p (R exactci 0.000675182658686321)', rr['pairs'][0]['p'], 0.000675182658686321, rel=1e-12)
check.near('the rate ratio (R: 2.10999757175465)', rr['pairs'][0]['estimate'], 2.10999757175465, rel=1e-12)
pl, pu = stats.beta.ppf(0.025, 60, 31), stats.beta.ppf(0.975, 61, 30)
check.near('exact conditional interval = Clopper-Pearson of 60 of 90, as a ratio (R poisson.test)', rr['pairs'][0]['lower'], float(pl / (1 - pl) * 54308.7 / 51477.5))
check.near('its upper limit', rr['pairs'][0]['upper'], float(pu / (1 - pu) * 54308.7 / 51477.5))
lvr = {l['level']: l for l in rr['levels']}
check('level totals', (lvr['A']['count'], lvr['A']['exposure'], lvr['B']['count']), (60.0, 51477.5, 30.0))
lo_, hi_ = smr.confint_poisson(60, 51477.5, method='exact-c')
check.near('a level\'s exact (Garwood) interval = confint_poisson', lvr['A']['lower'], float(lo_))
rs = call('fitybyx.oneway_rates', table=tgu, y='events', x='arm', exposure='py', method='score', ci_method='score', control='B')
ci_s = smr.confint_poisson_2indep(60, 51477.5, 30, 54308.7, method='score', compare='ratio')
check.near('score interval = confint_poisson_2indep', rs['pairs'][0]['lower'], float(ci_s[0]), rel=1e-9)
check.near('score test at the interval\'s limit: p = 0.05', float(smr.test_poisson_2indep(60, 51477.5, 30, 54308.7, value=rs['pairs'][0]['upper'], method='score').pvalue), 0.05, rel=1e-6)
# Ng, Gu and Tang (2007): the difference of rates, 41 in 28010 against 15 in 19017, one-sided
tng = table({'k': [41.0, 15.0], 'grp': ['one', 'two'], 'e': [28010.0, 19017.0]})
for meth, (st_, pv) in (('wald', (2.2047, 0.0137)), ('score', (2.0818, 0.0187)), ('etest-wald', (2.2047, 0.0184)), ('etest-score', (2.0818, 0.0179))):
    rr = call('fitybyx.oneway_rates', table=tng, y='k', x='grp', exposure='e', compare='diff', method=meth, ci_method='score', control='two')
    check.near(f'Ng et al. difference, {meth}: statistic {st_}', rr['pairs'][0]['stat'], st_, abs_=6e-4)
    check.near(f'Ng et al. difference, {meth}: one-sided p {pv}', rr['pairs'][0]['p_greater'], pv, abs_=7e-4)
# every level: the Poisson GLM's likelihood ratio = its closed form from the totals
rng_r = np.random.default_rng(8)
gk = np.repeat(['a', 'b', 'c'], 30)
ek = rng_r.uniform(0.5, 3, 90)
yk = rng_r.poisson(np.array([1.0, 1.4, 2.2])[np.repeat([0, 1, 2], 30)] * ek).astype(float)
fk = rng_r.integers(1, 3, 90).astype(float)
tk = table({'y': yk, 'g': gk.tolist(), 'e': ek, 'f': fk})
rk = call('fitybyx.oneway_rates', table=tk, y='y', x='g', exposure='e', freq='f')
Ck = np.array([np.sum((yk * fk)[gk == v]) for v in 'abc'])
Ek = np.array([np.sum((ek * fk)[gk == v]) for v in 'abc'])
lr_closed = 2 * np.sum(Ck * np.log(Ck / (Ek * Ck.sum() / Ek.sum())))
check.near('LR chi-square of the Poisson GLM = 2ΣC log(C/(E·rate))', rk['lr']['chisq'], float(lr_closed), rel=1e-7)
full = sm.GLM(yk, pd.get_dummies(gk).to_numpy(float), family=sm.families.Poisson(), exposure=ek, freq_weights=fk).fit()
check.near('the dispersion = Pearson χ²/DF of the GLM', rk['lr']['dispersion'], float(full.pearson_chi2 / full.df_resid))
check('three pairs of three levels', [(p_['i'], p_['j']) for p_ in rk['pairs']], [(1, 0), (2, 0), (2, 1)])
t21 = smr.test_poisson_2indep(Ck[2], Ek[2], Ck[1], Ek[1], method='score')
check.near('Freq counts units: a pair\'s score test on the totals', [p_ for p_ in rk['pairs'] if (p_['i'], p_['j']) == (2, 1)][0]['p'], float(t21.pvalue))
# a level without events: the score interval by root finding, the LR from the totals
tz = table({'events': [0.0, 0, 0, 2, 1, 2], 'arm': ['A'] * 3 + ['B'] * 3})
rz = call('fitybyx.oneway_rates', table=tz, y='events', x='arm')
pz = rz['pairs'][0]
check('zero events: the ratio is infinite, the upper limit too', (pz['estimate'], pz['upper']), ('Infinity', 'Infinity'))
with np.errstate(divide='ignore'):   # statsmodels divides by the zero rate on the way
    p_at_lower = float(smr.test_poisson_2indep(5, 3, 0, 3, value=pz['lower'], method='score').pvalue)
check.near('zero events: at the lower limit the score test gives p = 0.05', p_at_lower, 0.05, rel=1e-6)
check.near('zero events: the lower limit in closed form, count₁·(units₂/units₁)/z²', pz['lower'], 5 / stats.norm.ppf(0.975) ** 2, rel=1e-8)
check('zero events: the LR test from the totals, with a note', (rz['lr']['source'], any('no events' in t for t in rz['notes'])), ('totals', True))
check('zero events: no warnings reach the report', 'warnings' in rz, False)
check('counts only', 'error' in call('fitybyx.oneway_rates', table=table({'y': [0.5, 1, 2], 'g': ['a', 'b', 'a']}), y='y', x='g'), True)
check('a method for the other comparison is refused', 'error' in call('fitybyx.oneway_rates', table=tgu, y='events', x='arm', compare='diff', method='exact-cond'), True)

# ---- Contingency ▸ Two Sample Test for Proportions ------------------------------------------------
from statsmodels.stats.proportion import confint_proportions_2indep, test_proportions_2indep  # noqa: E402
# JMP's documented example (Car Poll: married 95 of 138 women, 101 of 165 men): the adjusted Wald
# difference 0.0763, interval [-0.03175, 0.181621], p = 0.1686
tcar = table({'sex': ['Female', 'Female', 'Male', 'Male'], 'marital': ['Married', 'Single', 'Married', 'Single'], 'n': [95.0, 43, 101, 64]})
r = call('fitybyx.contingency_twoprop', table=tcar, y='marital', x='sex', freq='n')
ac = [m for m in r['methods'] if m['key'] == 'agresti-caffo'][0]
check.near('JMP example: the difference 0.0763', r['estimate'], 0.0763, abs_=5e-5)
check.near('JMP example: lower limit -0.03175', ac['lower'], -0.03175, abs_=5e-6)
check.near('JMP example: upper limit 0.181621', ac['upper'], 0.181621, abs_=2e-6)
check.near('JMP example: adjusted Wald p 0.1686', ac['p'], 0.1686, abs_=5e-5)
check('the description', r['description'], 'P(Married|Female) − P(Married|Male)')
# R PropCIs and Fagerland et al. (2015) for 7 of 34 against 1 of 34
t734 = table({'g': ['a'] * 34 + ['b'] * 34, 'r': ['yes'] * 7 + ['no'] * 27 + ['yes'] * 1 + ['no'] * 33}, levels={'r': ['yes', 'no']})
r = call('fitybyx.contingency_twoprop', table=t734, y='r', x='g')
M = {m['method']: m for m in r['methods']}
check.near('PropCIs wald2ci(adjust="AC"): 0.01161167', M['Agresti-Caffo (adjusted Wald, as JMP)']['lower'], 0.01161167, abs_=6e-7)
check.near('PropCIs wald2ci(adjust="AC"): 0.32172166', M['Agresti-Caffo (adjusted Wald, as JMP)']['upper'], 0.32172166, abs_=6e-7)
check.near('PropCIs wald2ci(adjust="Wald"): 0.02916942', M['Wald']['lower'], 0.02916942, abs_=6e-7)
check.near('Fagerland: Newcombe hybrid score 0.019 to 0.340', M['Newcombe (hybrid score)']['upper'], 0.340, abs_=0.005)
check('Newcombe: an interval without a test', M['Newcombe (hybrid score)']['p'], None)
ref_mn = confint_proportions_2indep(7, 34, 1, 34, method='score', compare='diff', correction=True)
check.near('Miettinen-Nurminen = confint_proportions_2indep(score)', M['Miettinen-Nurminen (score)']['lower'], float(ref_mn[0]))
check.near('its test = test_proportions_2indep(score)', M['Miettinen-Nurminen (score)']['p'], float(test_proportions_2indep(7, 34, 1, 34, method='score', compare='diff').pvalue))
check.near('score test at the score limit: p = 0.05', float(test_proportions_2indep(7, 34, 1, 34, value=M['Miettinen-Nurminen (score)']['upper'], method='score', compare='diff').pvalue), 0.05, rel=1e-6)
r = call('fitybyx.contingency_twoprop', table=t734, y='r', x='g', compare='ratio')
M = {m['method']: m for m in r['methods']}
check.near('PropCIs riskscoreci (Koopman): 1.220853', M['Koopman (score)']['lower'], 1.220853, abs_=6e-7)
check.near('PropCIs riskscoreci (Koopman): 42.575718', M['Koopman (score)']['upper'], 42.575718, abs_=6e-6)
check.near('Fagerland: Katz log 0.91 to 54', M['Katz (log)']['upper'], 54, rel=0.01)
check.near('Fagerland: adjusted log 0.92 to 27', M['Adjusted log (0.5 added)']['upper'], 27, rel=0.01)
check.near('the relative risk 7', r['estimate'], 7.0)
r = call('fitybyx.contingency_twoprop', table=t734, y='r', x='g', compare='odds-ratio')
M = {m['method']: m for m in r['methods']}
check.near('PropCIs orscoreci: 1.246309', M['Miettinen-Nurminen (score)']['lower'], 1.246309, rel=5e-4)
check.near('PropCIs orscoreci: 56.486130', M['Miettinen-Nurminen (score)']['upper'], 56.486130, rel=5e-4)
check.near('Fagerland: Woolf logit 0.99 to 74', M['Woolf (logit)']['upper'], 74, rel=0.01)
check.near('Fagerland: Gart adjusted logit 0.98 to 38', M['Gart (adjusted logit, 0.5 added)']['upper'], 38, rel=0.01)
check.near('Fagerland: independence-smoothed logit 0.99 to 60', M['Independence-smoothed logit']['upper'], 60, rel=0.01)
check.near('the odds ratio (7/27)/(1/33)', r['estimate'], (7 / 27) / (1 / 33))
r = call('fitybyx.contingency_twoprop', table=t734, y='r', x='g', response='no')
check.near('Response Level no: the difference of the other level', r['estimate'], 27 / 34 - 33 / 34)
t0 = table({'g': ['a'] * 34 + ['b'] * 34, 'r': ['yes'] * 7 + ['no'] * 27 + ['no'] * 34}, levels={'r': ['yes', 'no']})
r = call('fitybyx.contingency_twoprop', table=t0, y='r', x='g', compare='odds-ratio')
M = {m['method']: m for m in r['methods']}
check('a zero cell: Woolf is not defined, Gart is', (M['Woolf (logit)']['lower'], M['Woolf (logit)'].get('note'), M['Gart (adjusted logit, 0.5 added)']['lower'] is not None), (None, 'not defined with a zero count', True))
check('a zero cell: no warnings reach the report', 'warnings' in r, False)

# ---- Contingency ▸ Cochran Mantel Haenszel: Breslow-Day (R DescTools) -------------------------------
def strata_table(tabs):
    s_, x_, y_, f_ = [], [], [], []
    for k_, tb in enumerate(tabs):
        for i_ in range(2):
            for j_ in range(2):
                s_.append(f's{k_ + 1}'); x_.append(['x1', 'x2'][i_]); y_.append(['y1', 'y2'][j_]); f_.append(float(tb[i_][j_]))
    return table({'s': s_, 'x': x_, 'y': y_, 'f': f_})


# statsmodels' TestStratified2: DescTools BreslowDayTest(correct=FALSE) 1.8438, p 0.7645; TRUE 1.8436, p 0.7645;
# mantelhaen.test: 11.8852 (with the continuity correction), p 0.0005658, odds ratio 3.5912 (1.781135 to 7.240633)
ts2 = strata_table([[[20, 14], [10, 24]], [[15, 12], [3, 15]], [[3, 2], [3, 2]], [[12, 3], [7, 5]], [[1, 0], [3, 2]]])
r = call('fitybyx.contingency_cmh', table=ts2, y='y', x='x', strata='s', freq='f')
check.near('Breslow-Day (DescTools 1.8438)', r['breslow_day']['chisq'], 1.8438, abs_=1e-4)
check.near('Breslow-Day p (0.7645)', r['breslow_day']['p'], 0.7645, abs_=1e-4)
check.near('Breslow-Day-Tarone (DescTools 1.8436)', r['breslow_day_tarone']['chisq'], 1.8436, abs_=1e-4)
check.near('CMH with the continuity correction (mantelhaen.test 11.8852)', r['cmh_cc']['chisq'], 11.8852, abs_=1e-4)
check.near('its p (0.0005658)', r['cmh_cc']['p'], 0.0005658, abs_=1e-7)
check.near('Mantel-Haenszel odds ratio (3.5912)', r['or_mh'], 3.5912, abs_=1e-4)
check.near('its lower limit (1.781135)', r['lower'], 1.781135, abs_=1e-6)
check('a stratum with a zero cell has no odds ratio of its own', [s_['or'] is None for s_ in r['by_stratum']], [False, False, False, False, True])
check.near('a stratum\'s odds ratio (20·24)/(14·10)', r['by_stratum'][0]['or'], 20 * 24 / (14 * 10))
# TestStratified3 (the Berkeley admissions tables): DescTools 18.83297, p 0.002064786, Tarone the same
ts3 = strata_table([[[313, 512], [19, 89]], [[207, 353], [8, 17]], [[205, 120], [391, 202]], [[278, 139], [244, 131]], [[138, 53], [299, 94]], [[351, 22], [317, 24]]])
r = call('fitybyx.contingency_cmh', table=ts3, y='y', x='x', strata='s', freq='f')
check.near('Breslow-Day, six strata (DescTools 18.83297)', r['breslow_day']['chisq'], 18.83297, rel=1e-6)
check.near('its p (0.002064786)', r['breslow_day']['p'], 0.002064786, rel=1e-5)
check.near('Breslow-Day-Tarone (18.83297)', r['breslow_day_tarone']['chisq'], 18.83297, rel=1e-4)
check.near('pooled odds ratio 1.101879', r['or_mh'], 1.101879, rel=1e-6)
check.near('CMH corrected 1.3368', r['cmh_cc']['chisq'], 1.3368, abs_=1e-4)
from statsmodels.stats.contingency_tables import StratifiedTable as _ST  # noqa: E402
check.near('the pooled relative risk = StratifiedTable.riskratio_pooled', r['rr_mh'], float(_ST([np.array(t_) for t_ in [[[313, 512], [19, 89]], [[207, 353], [8, 17]], [[205, 120], [391, 202]], [[278, 139], [244, 131]], [[138, 53], [299, 94]], [[351, 22], [317, 24]]]]).riskratio_pooled))
# TestStratified1: mantelhaen.test 3.9286 (corrected), p 0.04747, odds ratio 7 (1.026713 to 47.725133)
ts1 = strata_table([[[0, 0], [6, 5]], [[3, 0], [3, 6]], [[6, 2], [0, 4]], [[5, 6], [1, 0]], [[2, 5], [0, 0]]])
r = call('fitybyx.contingency_cmh', table=ts1, y='y', x='x', strata='s', freq='f')
check('strata without both levels of X and Y are left out', r['strata'], 3)
check.near('the other strata give R\'s mantelhaen.test: 3.9286 (corrected)', r['cmh_cc']['chisq'], 3.9286, abs_=1e-4)
check.near('its p (0.04747)', r['cmh_cc']['p'], 0.04747, abs_=1e-5)
check.near('the pooled odds ratio 7', r['or_mh'], 7.0)
check.near('its interval (1.026713 to 47.725133)', r['upper'], 47.725133, rel=1e-6)

# ---- Matched Pairs ▸ binary responses: Cochran's Q and McNemar ------------------------------------------
# Conover's example (NIST Dataplot): Q = 2.8, p = 0.246597
xq = np.array([[1, 1, 1], [1, 1, 1], [0, 1, 0], [1, 1, 0], [0, 0, 0], [1, 1, 1], [1, 1, 1], [1, 1, 0], [0, 0, 1], [0, 1, 0], [1, 1, 1], [1, 1, 1]], float)
tq = table({'a': xq[:, 0], 'b': xq[:, 1], 'c': xq[:, 2]})
r = call('matchedpairs.binary', table=tq, columns=['a', 'b', 'c'])
check.near('Cochran\'s Q, Conover (2.8)', r['cochran']['q'], 2.8)
check.near('its p (0.246597)', r['cochran']['p'], 0.246597, abs_=5e-7)
check('its DF and the success level', (r['cochran']['df'], r['success']), (2, '1'))
Cc, Rr = xq.sum(0), xq.sum(1)
qf = (3 - 1) * (3 * np.sum(Cc ** 2) - Cc.sum() ** 2) / (3 * Rr.sum() - np.sum(Rr ** 2))
check.near('Q by the formula (k − 1)(kΣC² − N²)/(kN − ΣR²)', r['cochran']['q'], float(qf))
# the same as text, and the other level as the success: the same Q
lab = np.where(xq == 1, 'pass', 'fail')
tq2 = table({'a': lab[:, 0].tolist(), 'b': lab[:, 1].tolist(), 'c': lab[:, 2].tolist()})
r2 = call('matchedpairs.binary', table=tq2, columns=['a', 'b', 'c'], success='fail')
check('text responses: the same Q whichever level is the success', (round(r2['cochran']['q'], 12), r2['success'], r2['columns'][0]['count']), (2.8, 'fail', 4))
# an example checked against the web (13.2857143, 0.00405776), and SAS's frequency-form example (8.4706, 0.0145)
d4 = np.array([[0, 0, 0, 1], [0, 0, 0, 1], [0, 0, 0, 1], [1, 1, 1, 1], [1, 0, 0, 1], [0, 1, 0, 1], [1, 0, 0, 1], [0, 0, 0, 1], [0, 1, 0, 0], [0, 0, 0, 0], [1, 0, 0, 1], [0, 0, 1, 1]], float)
r = call('matchedpairs.binary', table=table({f'q{j}': d4[:, j] for j in range(4)}), columns=[f'q{j}' for j in range(4)])
check.near('Cochran\'s Q of four responses (13.2857143)', r['cochran']['q'], 13.2857143, rel=1e-7)
check.near('its p (0.00405776)', r['cochran']['p'], 0.00405776, rel=1e-6)
cases = np.array([[0, 0, 0], [1, 0, 0], [0, 0, 1], [1, 0, 1], [0, 1, 0], [1, 1, 0], [0, 1, 1], [1, 1, 1]])
dsas = np.repeat(cases, [6, 2, 16, 4, 2, 6, 4, 6], 0).astype(float)
r = call('matchedpairs.binary', table=table({'A': dsas[:, 0], 'B': dsas[:, 1], 'C': dsas[:, 2]}), columns=['A', 'B', 'C'])
check.near('SAS example: Q 8.4706', r['cochran']['q'], 8.4706, abs_=5e-5)
check.near('SAS example: p 0.0145', r['cochran']['p'], 0.0145, abs_=5e-5)
# McNemar: R's mcnemar.test of [[101, 121], [59, 33]] (statsmodels' tests), the Vassar exact p 0.000004
mc = np.repeat([[1, 1], [1, 0], [0, 1], [0, 0]], [101, 121, 59, 33], axis=0).astype(float)
tmc = table({'u': mc[:, 0], 'v': mc[:, 1]})
r = call('matchedpairs.binary', table=tmc, columns=['u', 'v'], correction=True)
check.near('McNemar with the correction (R 20.67222)', r['pairs'][0]['chisq'], 20.67222, rel=1e-6)
check.near('its p (R 5.450095e-06)', r['pairs'][0]['p'], 5.450095e-06, rel=1e-6)
check.near('exact McNemar p (0.000004)', r['pairs'][0]['p_exact'], 0.000004, abs_=5e-7)
r = call('matchedpairs.binary', table=tmc, columns=['u', 'v'])
check.near('McNemar without the correction (R 21.35556)', r['pairs'][0]['chisq'], 21.35556, rel=1e-6)
check.near('its p (R 3.815136e-06)', r['pairs'][0]['p'], 3.815136e-06, rel=1e-6)
check.near('two responses: Cochran\'s Q is McNemar without the correction', r['cochran']['q'], r['pairs'][0]['chisq'])
check('the discordant counts b and c', (r['pairs'][0]['n10'], r['pairs'][0]['n01']), (121, 59))
check.near('the difference of the proportions, second minus first', r['pairs'][0]['diff'], (101 + 59) / 314 - (101 + 121) / 314)
# no discordant pair: statsmodels would give inf (p 0) with the correction; here chi-square 0, p 1
tnd = table({'u': [1.0, 1, 0, 0, 1], 'v': [1.0, 1, 0, 0, 1]})
r = call('matchedpairs.binary', table=tnd, columns=['u', 'v'], correction=True)
check('no discordant pair: χ² 0, p 1, exact p 1, a note', (r['pairs'][0]['chisq'], r['pairs'][0]['p'], r['pairs'][0]['p_exact'], r['cochran'], len(r['notes'])), (0.0, 1.0, 1.0, None, 2))
check('no warnings reach the report', 'warnings' in r, False)
teq = table({'u': [1.0] * 5 + [0.0] * 5, 'v': [0.0] * 5 + [1.0] * 5})
check('b = c with the correction: χ² 0 as in R (statsmodels: 1/(b + c))', call('matchedpairs.binary', table=teq, columns=['u', 'v'], correction=True)['pairs'][0]['chisq'], 0.0)
# missing values: Cochran on complete rows, each pair on its own
xm = xq.copy()
xm[2, 2] = np.nan
r = call('matchedpairs.binary', table=table({'a': xm[:, 0], 'b': xm[:, 1], 'c': xm[:, 2]}), columns=['a', 'b', 'c'])
check('a missing response: Cochran on 11 rows, the pair a-b on 12', (r['cochran']['n'], r['pairs'][0]['n'], r['pairs'][1]['n']), (11, 12, 11))
check('three values are not binary', 'error' in call('matchedpairs.binary', table=table({'a': [0.0, 1, 2], 'b': [1.0, 0, 1]}), columns=['a', 'b']), True)
r = call('matchedpairs.binary', table=tq, columns=['a', 'b', 'c'], exact=True)
check.near('Holm over the pairs\' exact p-values', r['pairs'][2]['p_holm'], float(multipletests([p_['p_exact'] for p_ in r['pairs']], method='holm')[1][2]))

# ---- the Python under the results runs on a CSV export of the table ----------------------------
import contextlib
import io
import os
import tempfile
import warnings


def code_runs(label, columns, results):
    with tempfile.TemporaryDirectory() as tmp:
        pd.DataFrame(columns).to_csv(os.path.join(tmp, 'data.csv'), index=False)
        here = os.getcwd()
        os.chdir(tmp)
        try:
            for name, res in results:
                ok = True
                try:
                    with contextlib.redirect_stdout(io.StringIO()), warnings.catch_warnings():
                        warnings.simplefilter('ignore')
                        exec(compile(res['code'], name, 'exec'), {})
                except Exception as e:   # the check below reports it
                    ok = f'{type(e).__name__}: {e}'
                check(f'{label}: the code of {name} runs', ok, True)
        finally:
            os.chdir(here)


cols = {'height': xb, 'weight': yb, 'w': wb, 'f': fb, 'sex': gb}
tidc = table(cols)
code_runs('Bivariate', cols, [(fn, call(fn, table=tidc, y='weight', x='height', **kw)) for fn, kw in [
    ('fitybyx.fit_poly', {'degree': 2}), ('fitybyx.fit_poly', {'degree': 1, 'weight': 'w', 'freq': 'f'}), ('fitybyx.fit_mean', {}),
    ('fitybyx.fit_special', {'ytr': 'log', 'xtr': 'sqrt'}), ('fitybyx.fit_special', {'intercept': 0}), ('fitybyx.fit_spline', {'lam': 10}),
    ('fitybyx.fit_lowess', {'frac': 0.5}), ('fitybyx.fit_each', {}), ('fitybyx.fit_robust', {}), ('fitybyx.fit_orthogonal', {}),
    ('fitybyx.density_ellipse', {'levels': [0.9]}), ('fitybyx.nonpar_density', {}), ('fitybyx.fit_quantile', {'tau': 0.5}), ('fitybyx.bivariate', {})]])
cols = {'y': yo, 'g': g.tolist(), 'blk': blk.tolist(), 'f': fo}
tidc = table(cols)
code_runs('Oneway', cols, [(f'{fn} {kw}', call(fn, table=tidc, y='y', x='g', **kw)) for fn, kw in [
    ('fitybyx.oneway', {}), ('fitybyx.oneway', {'block': 'blk'}), ('fitybyx.oneway_compare', {'method': 'student'}), ('fitybyx.oneway_compare', {'method': 'tukey'}),
    ('fitybyx.oneway_compare', {'method': 'dunnett', 'control': 'A'}), ('fitybyx.oneway_nonpar', {'test': 'wilcoxon'}), ('fitybyx.oneway_nonpar', {'test': 'median'}),
    ('fitybyx.oneway_nonpar', {'test': 'vdw'}), ('fitybyx.oneway_nonpar_mc', {'method': 'dunn_all'}), ('fitybyx.oneway_unequal_var', {}),
    ('fitybyx.oneway_equivalence', {'delta': 1}), ('fitybyx.oneway_power', {}), ('fitybyx.oneway_anom', {}), ('fitybyx.oneway_densities', {})]])
cols2 = {'y': np.concatenate([groups[0], groups[1]]), 'g': ['A'] * nlev[0] + ['B'] * nlev[1]}
tidc = table(cols2)
code_runs('Oneway, two levels', cols2, [(fn, call(fn, table=tidc, y='y', x='g')) for fn in ('fitybyx.oneway_ttest', 'fitybyx.oneway_ks')])
cols = {'dose': dose, 'response': resp.tolist(), 'f': wl, 'k': cat3.tolist(), 'sev': names.tolist()}
tidc = table(cols, types={'sev': 'ordinal'}, levels={'response': ['no', 'yes'], 'sev': ['none', 'mild', 'moderate', 'severe']})
code_runs('Logistic', cols, [(f'{y_} {kw}', call('fitybyx.logistic', table=tidc, y=y_, x='dose', **kw)) for y_, kw in [('response', {}), ('response', {'freq': 'f'}), ('k', {}), ('sev', {})]])
cols = {'trt': tx.tolist(), 'out': ty.tolist()}
tidc = table(cols, types={'trt': 'ordinal', 'out': 'ordinal'}, levels={'trt': ['placebo', 'low', 'high'], 'out': ['none', 'some', 'good']})
code_runs('Contingency', cols, [(fn, call(fn, table=tidc, y='out', x='trt')) for fn in ('fitybyx.contingency', 'fitybyx.contingency_measures', 'fitybyx.contingency_ca')])
check('agreement of columns without a level in common', 'error' in call('fitybyx.contingency_agreement', table=tidc, y='out', x='trt'), True)
code_runs('Agreement', {'r1': t2x.tolist(), 'r2': t2y.tolist()}, [('fitybyx.contingency_agreement', call('fitybyx.contingency_agreement', table=tid7, y='r2', x='r1'))])
cols = {'t': x2.tolist(), 'r': y2.tolist()}
tidc = table(cols, levels={'t': ['drug', 'placebo'], 'r': ['yes', 'no']})
code_runs('2x2', cols, [(fn, call(fn, table=tidc, y='r', x='t')) for fn in ('fitybyx.contingency', 'fitybyx.contingency_2x2', 'fitybyx.contingency_trend', 'fitybyx.contingency_anomp')])
cols = {'city': cities, 'smoking': xs_, 'lung': ys_, 'n': fs_}
tidc = table(cols, levels={'smoking': ['smoker', 'nonsmoker'], 'lung': ['cancer', 'healthy']})
code_runs('CMH', cols, [('fitybyx.contingency_cmh', call('fitybyx.contingency_cmh', table=tidc, y='lung', x='smoking', strata='city', freq='n'))])
cols = {'before': before, 'after': after, 'grp': grp}
tidc = table(cols)
code_runs('Matched Pairs', cols, [('matchedpairs.analyze', call('matchedpairs.analyze', table=tidc, y1='before', y2='after', group='grp'))])



def code_ns(columns, code, label):
    """Run a result's code on a CSV export of its table; its variables."""
    with tempfile.TemporaryDirectory() as tmp:
        pd.DataFrame(columns).to_csv(os.path.join(tmp, 'data.csv'), index=False)
        here = os.getcwd()
        os.chdir(tmp)
        ns = {}
        try:
            with contextlib.redirect_stdout(io.StringIO()), warnings.catch_warnings():
                warnings.simplefilter('ignore')
                exec(compile(code, label, 'exec'), ns)
        except Exception as e:   # the check below reports it
            ns['__error__'] = f'{type(e).__name__}: {e}'
        finally:
            os.chdir(here)
    check(f'the code of {label} runs', ns.get('__error__', True), True)
    return ns


# the code under the new results gives the report's numbers
cols = {'score': sc_lv * 2, 'trt': ['new'] * 5 + ['active'] * 5, 'n': new_n + act_n}
res_ = call('fitybyx.oneway_brunner', table=tmh, y='score', x='trt', freq='n', tost={'low': 0.4, 'upp': 0.6})
ns = code_ns(cols, res_['code'], 'Brunner-Munzel with Freq')
if 'r' in ns:
    check.near('its code: the probability of superiority', float(ns['r'].prob1), res_['pairs'][0]['prob'])
    check.near('its code: the Brunner-Munzel p', float(ns['r'].pvalue), res_['pairs'][0]['p'])
cols = {'y': yk, 'g': gk.tolist(), 'e': ek, 'f': fk}
res_ = call('fitybyx.oneway_rates', table=tk, y='y', x='g', exposure='e', freq='f')
ns = code_ns(cols, res_['code'], 'Compare Rates with exposure and Freq')
if 'full' in ns:
    check.near('its code: the likelihood ratio of the GLMs', float(2 * (ns['full'].llf - ns['null'].llf)), res_['lr']['chisq'], rel=1e-7)
    check.near('its code: the first pair\'s score test', float(smr.test_poisson_2indep(ns['c1'], ns['e1'], ns['c2'], ns['e2'], method='score').pvalue), res_['pairs'][0]['p'])
    check.near('its code: the dispersion', float(ns['full'].pearson_chi2 / ns['full'].df_resid), res_['lr']['dispersion'], rel=1e-7)
cols = {'events': [20.0, 25, 15, 10, 12, 8], 'arm': ['A'] * 3 + ['B'] * 3, 'py': [17000.0, 20000.0, 14477.5, 18000.0, 20000.0, 16308.7]}
res_ = call('fitybyx.oneway_rates', table=tgu, y='events', x='arm', exposure='py', method='exact-cond', ci_method='exact-cond', control='B')
ns = code_ns(cols, res_['code'], 'Compare Rates, exact conditional')
if 'pl' in ns:
    check.near('its code: the exact conditional interval', float(ns['pl'] / (1 - ns['pl']) * ns['e2'] / ns['e1']), res_['pairs'][0]['lower'])
cols = {'g': ['a'] * 34 + ['b'] * 34, 'r': ['yes'] * 7 + ['no'] * 27 + ['yes'] * 1 + ['no'] * 33}
for cmp_ in ('diff', 'ratio', 'odds-ratio'):
    res_ = call('fitybyx.contingency_twoprop', table=t734, y='r', x='g', compare=cmp_)
    ns = code_ns(cols, res_['code'], f'Two Sample Test for Proportions ({cmp_})')
    if 'count1' in ns:
        check('its code: the counts', [float(ns[k]) for k in ('count1', 'nobs1', 'count2', 'nobs2')], [res_['count1'], res_['nobs1'], res_['count2'], res_['nobs2']])
        m_ = res_['methods'][-1]
        check.near('its code: the last method\'s interval', float(confint_proportions_2indep(ns['count1'], ns['nobs1'], ns['count2'], ns['nobs2'], method=m_['key'], compare=cmp_, correction=m_['correction'])[1]), m_['upper'])
cols = {'sex': ['Female', 'Female', 'Male', 'Male'], 'marital': ['Married', 'Single', 'Married', 'Single'], 'n': [95, 43, 101, 64]}
res_ = call('fitybyx.contingency_twoprop', table=tcar, y='marital', x='sex', freq='n')
ns = code_ns(cols, res_['code'], 'Two Sample Test for Proportions with Freq')
if 'count1' in ns:
    check('its code: the counts with Freq', [float(ns[k]) for k in ('count1', 'nobs1', 'count2', 'nobs2')], [95.0, 138.0, 101.0, 165.0])
for label_, tbl_, tabs_ in (('Breslow-Day (DescTools)', ts2, [[[20, 14], [10, 24]], [[15, 12], [3, 15]], [[3, 2], [3, 2]], [[12, 3], [7, 5]], [[1, 0], [3, 2]]]),):
    res_ = call('fitybyx.contingency_cmh', table=tbl_, y='y', x='x', strata='s', freq='f')
    s_, x_, y_, f_ = [], [], [], []
    for k_, tb in enumerate(tabs_):
        for i_ in range(2):
            for j_ in range(2):
                s_.append(f's{k_ + 1}'); x_.append(['x1', 'x2'][i_]); y_.append(['y1', 'y2'][j_]); f_.append(float(tb[i_][j_]))
    ns = code_ns({'s': s_, 'x': x_, 'y': y_, 'f': f_}, res_['code'], label_)
    if 'st' in ns:
        check.near('its code: Breslow-Day', float(ns['st'].test_equal_odds().statistic), res_['breslow_day']['chisq'])
        check.near('its code: the pooled odds ratio', float(ns['st'].oddsratio_pooled), res_['or_mh'])
res_ = call('fitybyx.contingency_cmh', table=tid10, y='lung', x='smoking', strata='city', freq='n')
ns = code_ns({'city': cities, 'smoking': xs_, 'lung': ys_, 'n': fs_}, res_['code'], 'CMH of the Chinese smoking tables, Freq')
if 'st' in ns:
    check.near('its code: the Mantel-Haenszel odds ratio with Freq', float(ns['st'].oddsratio_pooled), res_['or_mh'])
from statsmodels.stats.contingency_tables import cochrans_q  # noqa: E402
for label_, cols_ in (('Cochran\'s Q, numeric', {'a': xq[:, 0], 'b': xq[:, 1], 'c': xq[:, 2]}), ('Cochran\'s Q, text', {'a': lab[:, 0].tolist(), 'b': lab[:, 1].tolist(), 'c': lab[:, 2].tolist()})):
    res_ = call('matchedpairs.binary', table=table(cols_), columns=['a', 'b', 'c'])
    ns = code_ns(cols_, res_['code'], label_)
    if 'X' in ns:
        check.near('its code: Q', float(cochrans_q(ns['X'].to_numpy()).statistic), res_['cochran']['q'])
        check.near('its code: the first pair\'s exact McNemar', float(mcnemar(ns['t'], exact=True).pvalue), res_['pairs'][0]['p_exact'])
        check.near('its code: the first pair\'s McNemar χ²', float(mcnemar(ns['t'], exact=False, correction=False).statistic), res_['pairs'][0]['chisq'])

# ---- errors and row lists ---------------------------------------------------------------------
check('Y and X the same column', 'error' in call('fitybyx.fit_poly', table=tid, y='before', x='before'), True)
check('one level: no t test', 'error' in call('fitybyx.oneway_ttest', table=tid, y='before', x='grp', rows=[i for i in range(n) if grp[i] == 'x']), True)
check('rows=None is every row', call('fitybyx.fit_mean', table=tid, y='before', x='after', rows=None)['n'], float(okm.sum()))
sys.exit(check.done())
